################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean968578
distclean968578:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/bin ./mkconfigure
install: install-bin-554132
install-bin-554132: ./mkconfigure
	install -m 0755 -D ./mkconfigure /tmp/opt/bin/mkconfigure

