################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean58738
distclean58738:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./pofig
install: install-bin-450630
install-bin-450630: ./pofig
	install -m 0755 -D ./pofig /tmp/opt/share/formake/pofig

