################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean922338
distclean922338:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./confighelp
install: install-bin-513238
install-bin-513238: ./confighelp
	install -m 0755 -D ./confighelp /tmp/opt/share/formake/confighelp

