################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean944339
distclean944339:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./mkdep
install: install-bin-427918
install-bin-427918: ./mkdep
	install -m 0755 -D ./mkdep /tmp/opt/share/formake/mkdep

