#!/bin/sh

# This example demonstrates how mkdep can be used to be safe for parallel building (make -j)

$TOP_DIR=../
. $TOP_DIR/build.conf

rm -f Makefile

sources="file1.c file2.c file3.c"

for src in $sources; do
  obj=`list -suffix-ed o "_pic/$src"`
  dep=`list -suffix-ed d $obj`
  touch $dep
  cat >Makefile <<EOF
include $dep
$obj: $src
	cfront -c $PIC_FLAGS -o $obj $src
	mkdep -obj $obj $src >$dep

EOF
done

