#!/bin/sh
################################################################################
# This script was generated with the following command:
#  mkmkmf -srcroot ./ -subdirs src
#
#
# Important variables to use:
#   BUILDROOT        - relative path to the build root directory
#   CONF             - name of the build config file
#   MAKEFILE         - name of output Make file
#   TOOLS            - tools used in this script
#   SUBDIRS          - subdirectories to run mkmf in
#   SCRIPT           - name of this script
#   SRCDIR           - relative path to the source directory (mkmf location)
#   SRCROOT          - relative path to the source root directory (package top dir)
#   ASB_BUILDDIR     - absolute path to the build directory (current dir)
#   SUBDIR           - current directory path from BUILDROOT

################################################################################
# BASE CONFIGURATION
export BUILDROOT=.
CONF="build.conf"
MAKEFILE="Makefile"
TOOLS="relpath mkrule"
SUBDIRS="src"

################################################################################
# INIT
SCRIPT=`basename $0`
PATH=$FORMAKE:$PWD/$BUILDROOT/formake:$PATH
syscap test -f $TOOLS || exit 1
export SRCDIR=`dirname $0 | xargs relpath ./`
SRCROOT=`relpath ./ $SRCDIR/$BUILDROOT`
ABS_BUILDDIR=`pwd`
SUBDIR=`relpath $BUILDROOT ./`

################################################################################
# READ CONFIG
#. $BUILDROOT/$CONF

################################################################################
# INIT MAKEFILE
mkrule init >$MAKEFILE
mkrule distclean $MAKEFILE $CONF formake/'*.conf' >>$MAKEFILE

################################################################################
# CUSTOM CODE

################################################################################
# DIST
dist_files="configure formake/relpath formake/mkrule formake/optool formake/syscap mkmf "
mkrule dist -n $PACKAGE_NAME -ver $PACKAGE_VERSION -f $dist_files >>$MAKEFILE || exit 1

################################################################################
# SUBDIRS
mkrule subdir -all -install -clean -dist -distclean -d $SUBDIRS >>$MAKEFILE
for dir in $SUBDIRS; do
  cd $ABS_BUILDDIR
  test -d $dir || mkdir -p $dir
  cd $dir; $ABS_BUILDDIR/$SRCDIR/$dir/mkmf || exit 1
done

################################################################################
# DONE
echo "$SUBDIR/$SCRIPT: DONE"

