#!/bin/sh

################################################################################
# base configuration variables
TOPDIR=.
CONF="build.conf"
MAKEFILE="Makefile"

################################################################################
# go to package dir and set up PATH
cd `dirname "$0"`
PATH=$TOPDIR/mk:$PATH

################################################################################
# include toplevel config file
. $TOPDIR/$CONF

################################################################################
# set up dist name
DIST_NAME="$PACKAGE_NAME-$PACKAGE_VERSION"

################################################################################
# generate makefile
cat >$MAKEFILE <<EOF
all:
	\$(MAKE) -C src

install:
	\$(MAKE) -C src install

uninstall:
	\$(MAKE) -C src uninstall

clean: clean-local
	\$(MAKE) -C src clean

clean-local:

distclean: clean-local
	\$(MAKE) -C src distclean
	rm -f build.conf configure.log Makefile
	rm -f "${DIST_NAME}.tar.gz"

dist:
	rm -Rf             dist_tree
	mkdir              dist_tree
	mkdir              dist_tree/mk
	cp -R -P configure dist_tree
	cp -R -P mkmf      dist_tree
	cp -R -P COPYING   dist_tree
	cp -R -P mk/cltest dist_tree/mk
	cp -R -P mk/cmdok  dist_tree/mk
	cp -R -P mk/cppdef dist_tree/mk
	cp -R -P mk/cprobe dist_tree/mk
	cp -R -P mk/mkdep  dist_tree/mk
	cp -R -P mk/pofig  dist_tree/mk
	\$(MAKE) -C src dist-tree
	mv dist_tree $DIST_NAME
	tar -czvf "${DIST_NAME}.tar.gz" $DIST_NAME
	rm -Rf $DIST_NAME
EOF

./src/mkmf

echo "mkmf: DONE"

