################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean559112
distclean559112:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./relpath
install: install-bin-854825
install-bin-854825: ./relpath
	install -m 0755 -D ./relpath /tmp/opt/share/formake/relpath

