#!/bin/sh
#
# Formake libro
#
# Copyright (c) 2015-2018, Oleksiy Chernyavskyy
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

################################################################################
# SWITCH TO MODERN SHELL IF POSSIBLE
(test_exit_code_127_sdfjsdfksjdhfksjdhf  >/dev/null) 2>/dev/null
if test $? -ne 127; then
  if test -z "$FORMAKE_BASH_REDIRECTED"; then
    FORMAKE_BASH_REDIRECTED=1
    export FORMAKE_BASH_REDIRECTED
    if test -x /bin/bash; then
      exec /bin/bash "$0" ${1+"$@"}
    elif test -x /usr/bin/bash; then
      exec /usr/bin/bash "$0" ${1+"$@"}
    elif test -x /usr/local/bin/bash; then
      exec /usr/local/bin/bash "$0" ${1+"$@"}
    elif test -x /usr/pkg/bin/bash; then
      exec /usr/pkg/bin/bash "$0" ${1+"$@"}
    else
      (bash -c "pwd" >/dev/null) 2>/dev/null
      if test $? -eq 0; then
        exec bash "$0" ${1+"$@"}
      fi
    fi
  fi
fi
FORMAKE_BASH_REDIRECTED=
export FORMAKE_BASH_REDIRECTED
################################################################################


version_string="libro 0.3"
script_name=`basename "$0"`
orig_dir=`pwd`
sh_cmd=
sh_targets=
sh_lib_a=
sh_regular_files=
sh_lib_so=
sh_lib_so_c=
sh_lib_so_cra=
sh_symlinks=

if test -z "$CONFIG_AR"; then
  CONFIG_AR=ar
  export CONFIG_AR
fi

AR_FLAGS=rcs

cd_param=
(cd -P / >/dev/null) 2>/dev/null
if test $? -eq 0; then
  cd_param="-P"
fi
cd $cd_param $orig_dir


abs_path() {
  _sub_orig_dir=`pwd`
  if test $# = 0; then
    abs_path_ret=
    return
  fi
  if test $# = 2; then
    _arg_orig_dir=$1
    _arg=$2
    if echo "$_arg" | grep "^/" > /dev/null; then
      :
    else
      _arg=`echo "$_arg_orig_dir/$_arg" | sed 's!//*!/!g'`
    fi
  else
    _arg=$1
  fi
  if test -e "$_arg"; then
    if test -d $_arg; then
      _file=
    else
      _file=`basename "$_arg"`
      _arg=`dirname "$_arg"`
    fi

    cd $cd_param $_arg
    abs_path_ret=`pwd`
    if test x"$_file" != "x"; then
      abs_path_ret="$abs_path_ret/$_file"
    fi

    cd $cd_param $_sub_orig_dir
  else
    if echo "$_arg" | grep "^/" > /dev/null; then
      abs_path_ret="$_arg"
    else
      abs_path_ret="$_sub_orig_dir/$_arg"
    fi
    abs_path_ret=`echo "$abs_path_ret" | sed 's#//*#/#g'`
    abs_path_ret=`echo "$abs_path_ret" | sed 's#/*$#/#'`
    string_prev=
    while test "x$abs_path_ret" != "x$string_prev" ; do
      string_prev=$abs_path_ret
      abs_path_ret=`echo "$abs_path_ret" | sed 's#/[^/][^/][^/][^/]*/\.\./#/#g' | sed 's#/[^/][^/.]/\.\./#/#g' | sed 's#/[^/.][^/]/\.\./#/#g' | sed 's#/[^/.]/\.\./#/#g'`
      abs_path_ret=`echo "$abs_path_ret" | sed 's#^/\.\./#/#' | sed 's#^/\.\.$#/#'`
      abs_path_ret=`echo "$abs_path_ret" | sed 's#/\./#/#g' | sed 's#/\.$#/#'`
    done
    abs_path_ret=`echo "$abs_path_ret" | sed 's#/$##' | sed 's#^$#/#'`
  fi
}


print_help() {
  cat <<EOF
Build static and dynamic libraries

$script_name [static|shared] [-c++] -name NAME [-ver VERSION] -obj OBJECTS [-o DIR] [-ldflags=FLAGS] [-p] [-s]
 static           create static library (default)
 shared           create shared library
 -name NAME       library name 
 -ver X[.Y[.Z]]   library version in specified format
 -obj OBJECTS     object files
 -ldflags=FLAGS   LD flags
 -c++             use C++ linker
 -o DIR           output directory
 -p               only print commands that would be run
 -sh              generate Shell script in format VAR="VALUE"
 -s               silent mode
 -v               print version
EOF
}

print_version() {
  echo "$version_string"
}

run_command() {
  if test x$op_silent = x; then
    cat <<EOF
$@
EOF
  fi
  if test x$op_print_only = x; then
"$@"
  fi
  if test x$op_shrc = x1; then
    sh_cmd="$sh_cmd
$@"
  fi
}


mkstatic() {
  if test x$op_print_only = x; then
    cmdok -f $CONFIG_AR || exit 1
  fi

  lib_static="lib${op_name}.a"
  if test -n "$op_dir"; then
    lib_static="$op_dir/$lib_static"
  fi

  if test x$op_shrc = x1; then
    sh_targets="$sh_targets $lib_static"
    sh_lib_a="$sh_lib_a $lib_static"
    sh_regular_files="$sh_regular_files $lib_static"
  fi

  run_command rm -f $lib_static
  run_command $CONFIG_AR $AR_FLAGS $lib_static $op_obj
  run_command ranlib $lib_static
}

mkshared() {
  if test x$cxx_mode = x; then
    if test -z "$CONFIG_CC"; then
      formake_cprobe_exifer
    else
      formake_cprobe
    fi
    LIBRO_CC=$CONFIG_CC
    LIBRO_CC_TYPE=CONFIG_CC_TYPE
  else
    if test -z "$CONFIG_CXX"; then
      formake_cxxprobe_exifer
    else
      formake_cxxprobe
    fi
    LIBRO_CC=$CONFIG_CXX
    LIBRO_CC_TYPE=CONFIG_CXX_TYPE
  fi

  
  if test -n "$op_dir"; then
    out_dir="$op_dir/"
  else
    out_dir=
  fi

  if test -z "$op_age"; then
    age_pref=
  else
    age_pref=".${op_age}"
  fi

  orig_dir=`pwd`
  case "$LIBRO_CC_TYPE" in
    gcc|*)
      lib_so="lib${op_name}.so"
      lib_so_c="${lib_so}.${op_current}"
      lib_so_cra="${lib_so_c}.${op_revision}$age_pref"

      if test x$op_shrc = x1; then
        sh_targets="$sh_targets $out_dir$lib_so $out_dir$lib_so_c $out_dir$lib_so_cra"
        sh_lib_so="$sh_lib_so $out_dir$lib_so"
        sh_lib_so_c="$sh_lib_so_c $out_dir$lib_so_c"
        sh_lib_so_cra="$sh_lib_so_cra $out_dir$lib_so_cra"
        sh_regular_files="$sh_regular_files $out_dir$lib_so_cra"
        sh_symlinks="$sh_symlinks $out_dir$lib_so $out_dir$lib_so_c"
      fi

      run_command rm -f $out_dir$lib_so $out_dir$lib_so_c $out_dir$lib_so_cra
  	  run_command $LIBRO_CC -shared -fPIC -Wl,-soname,$lib_so_c -o $out_dir$lib_so_cra $op_obj $CONFIG_LDFLAGS
  	  run_command ln -s $lib_so_cra $out_dir$lib_so_c
  	  run_command ln -s $lib_so_cra $out_dir$lib_so
    ;;
  esac
}

case "$1" in
  static)
    lib_type=static
    shift
    ;;
  shared)
    lib_type=shared
    shift
    ;;
  *)
    lib_type=static
    ;;
esac

if test $# -eq 0; then
  echo "$script_name: additional parameters are missing" >&2
  exit 1
fi

current_opt=
while test $# -gt 0; do
  case "$1" in
    -h|-help|--help)
      print_help
      exit 0
      ;;
    -v)
      print_version
      exit 0
      ;;
    -name)
      op_name=
      current_opt=name
      ;;
    -ver)
      op_ver=
      current_opt=ver
      ;;
    -obj)
      op_obj=
      current_opt=obj
      ;;
    -ldflags=*)
      CONFIG_LDFLAGS=`echo "$1" | sed 's/^[^=]*=//'`
      export CONFIG_LDFLAGS
      current_opt=
      ;;
    -c++)
      cxx_mode=1
      current_opt=
      ;;
    -o)
      op_dir=
      current_opt=o
      ;;
    -p)
      op_print_only=1
      current_opt=
      ;;
    -s)
      op_silent=1
      current_opt=
      ;;
    -sh)
      op_shrc=1
      op_print_only=1
      op_silent=1
      current_opt=
      ;;
    *)
      case "$current_opt" in
        name)
          op_name=$1
          current_opt=
          ;;
        ver)
          _current=`echo "$1" | sed 's/\..*//'`
          rest=`echo "$1" | sed 's/^[^.]*\.*//'`
          _revision=`echo "$rest" | sed 's/\..*//'`
          rest=`echo "$rest" | sed 's/^[^.]*\.*//'`
          _age=`echo "$rest" | sed 's/\..*//'`
          op_ver=$1
          op_current=$_current
          op_revision=$_revision
          op_age=$_age
          current_opt=
          ;;
        o)
          op_dir=$1
          current_opt=
          ;;
        obj)
          op_obj="$op_obj $1"
          ;;
        *)
          echo "$script_name: invalid parameter $1" >&2
          exit 1
          ;;
      esac
      ;;
  esac
  shift
done

if test -z "$op_obj"; then
  echo "$script_name: objects not specified" >&2
  exit 1
fi

################################################################################
#CONFIG_MK_PATH
if test -z "$CONFIG_MK_PATH"; then
  cd $cd_param `dirname "$0"`
  if test -x $script_name; then
    CONFIG_MK_PATH=`pwd`
  elif test -d $CONFIG_SRCROOT/mk && test -x $CONFIG_SRCROOT/mk/$script_name; then
    cd $cd_param $CONFIG_SRCROOT/mk
    CONFIG_MK_PATH=`pwd`
  else
    IFS_save=$IFS
    IFS=:
    for dir in $PATH; do
      if test -f "$dir/$script_name" && test -x "$dir/$script_name" ; then
        abs_path "$dir"
        CONFIG_MK_PATH=$abs_path_ret
        break
      fi
    done
    IFS=$IFS_save
  fi

  if test -z "$CONFIG_MK_PATH"; then
    echo "$script_name: Formake modules not found" >&2
    exit 1
  fi

  export CONFIG_MK_PATH
  PATH="$CONFIG_MK_PATH:$PATH"
  export PATH
  cd $cd_param $orig_dir
fi
################################################################################

if test -f $CONFIG_MK_PATH/subscript; then
  . $CONFIG_MK_PATH/subscript
else
  echo "$script_name: module not found: subscript" >&2
  exit 1
fi
################################################################################

if test -z "$op_name"; then
  op_name=foo
fi

if test -z "$op_ver"; then
  op_ver="1.0.0"
  op_current=1
  op_revision=0
  op_age=0
elif test -z "$op_revision"; then
  op_revision=0
fi

if test -n "$op_dir" && test -z "$op_print_only"; then
  test -d "$op_dir" || mkdir -p $op_dir
  if test ! -d $op_dir; then
    echo "$script_name: cannot create output directory $op_dir" >&2
    exit 1
  fi
  cd $op_dir
  op_dir=`pwd`
  cd $orig_dir
elif test -n "$op_dir" && test x$op_shrc = x1; then
  sh_cmd="$sh_cmd
test -d $op_dir || mkdir -p $op_dir"
fi

if test $lib_type = static; then
  mkstatic
else
  mkshared
fi

if test x$op_shrc = x1; then
  sh_cmd=`echo "$sh_cmd" | sed '/^ *$/d'`
  sh_targets=`echo "$sh_targets" | sed 's/^ *//'`
  sh_lib_a=`echo "$sh_lib_a" | sed 's/^ *//'`
  sh_regular_files=`echo "$sh_regular_files" | sed 's/^ *//'`
  sh_lib_so=`echo "$sh_lib_so" | sed 's/^ *//'`
  sh_lib_so_c=`echo "$sh_lib_so_c" | sed 's/^ *//'`
  sh_lib_so_cra=`echo "$sh_lib_so_cra" | sed 's/^ *//'`
  sh_symlinks=`echo "$sh_symlinks" | sed 's/^ *//'`
  cat <<EOF
SH_CMD="$sh_cmd"
SH_TARGETS="$sh_targets"
SH_LIB_A="$sh_lib_a"
SH_REGULAR_FILES="$sh_regular_files"
SH_LIB_SO="$sh_lib_so"
SH_LIB_SO_C="$sh_lib_so_c"
SH_LIB_SO_CRA="$sh_lib_so_cra"
SH_SYMLINKS="$sh_symlinks"
EOF
fi

