#!/bin/sh
#
# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
#

VERSION=1.2
script_name=`basename $0`

print_help() {
  printf "list [-h|-help] [-version] [-grep <args ...> [-]] [-sed <args ...> [-]] [-rm-headers] [-rm-cfiles]\n"
  printf "     [-rm-cxxfiles] [-rm-objects] [-grep-headers] [-grep-cfiles]\n"
  printf "     [-grep-cxxfiles] [-grep-objects] [-pref=<prefix>] [-rm-suffix]\n"
  printf "     [-suffix-ed <suffix>] [-add-suffix <suffix>] [-ext=<extension> [-ifs <ifs>]\n"
  printf "     [-merge-lines] [-list] <list>\n"
}

if test $# -eq 0; then
  print_help
  exit 1
fi


param_sed=false
param_grep=false
param_rm_headers=false
param_rm_cfiles=false
param_rm_cxxfiles=false
param_rm_objects=false
param_grep_headers=false
param_grep_cfiles=false
param_grep_cxxfiles=false
param_grep_objects=false
param_add_prefix=false
param_add_suffix=false
param_suffix_ed=false
param_rm_suffix=false
param_ifs=false
param_merge_lines=false

noption=1
current_opt=""
list=
while test $# -gt 0; do
  opt_arg=false
  if test x"$current_opt" = "xlist"; then
    list="$list$1 "
  else
    case $1 in
    -help|-h)
      print_help
      exit 0
      ;;
    -version)
      printf "${VERSION}\n"
      exit 0
      ;;
    -sed)
      current_opt="sed"
      sed_args=
      ;;
    -grep)
      current_opt="grep"
      grep_args=
      ;;
    -rm-headers)
      param_rm_headers=true
      ;;
    -rm-cfiles)
      param_rm_cfiles=true
      ;;
    -rm-cxxfiles)
      param_rm_cxxfiles=true
      ;;
    -rm-objects)
      param_rm_objects=true
      ;;
    -grep-headers)
      param_grep_headers=true
      ;;
    -grep-cfiles)
      param_grep_cfiles=true
      ;;
    -grep-cxxfiles)
      param_grep_cxxfiles=true
      ;;
    -grep-objects)
      param_grep_objects=true
      ;;
    -pref=*)
      prefix=`echo -n "$1" | sed 's/^[^=]*=//'`
      param_add_prefix=true
      current_opt=
      ;;
    -rm-suffix)
      param_rm_suffix=true
      ;;
    -ext=*)
      suffix_ed=`echo -n "$1" | sed 's/^[^=]*=//'`
      param_suffix_ed=true
      current_opt=
      ;;
    -suffix-ed)
      current_opt="suffix-ed"
      ;;
    -add-suffix)
      current_opt="add-suffix"
      ;;
    -ifs)
      current_opt="ifs"
      ;;
    -merge-lines)
      param_merge_lines=true
      ;;
    -list)
      current_opt="list"
      ;;
    -)
      current_opt=
      ;;
    *)
      opt_arg=true
      case $current_opt in
      sed)
        param_sed=true
        if test x"$sed_args" = "x"; then
          sed_args=\'$1\'
        else
          sed_args="$sed_args '$1'"
        fi
        ;;
      grep)
        param_grep=true
        if test x"$grep_args" = "x"; then
          grep_args=\'$1\'
        else
          grep_args="$grep_args '$1'"
        fi
        ;;
      suffix-ed)
        param_suffix_ed=true
        suffix_ed=$1
        current_opt=
        ;;
      add-suffix)
        param_add_suffix=true
        add_suffix=$1
        current_opt=
        ;;
      ifs)
        param_ifs=true
        ifs=$1
        current_opt=
        ;;
      *)
        list="$list$1 "
        ;;
      esac
      ;;
    esac
  fi
  shift
  if $opt_arg; then
    false
  else
    noption=`expr $noption \+ 1`
  fi
done

  nl='
'

if test x"$list" = "x"; then
  IFS_save=$IFS
  IFS=$nl
  while read input; do
    if test x"$list" = "x"; then
      list=$input
    else
      list="${list}${nl}$input"
    fi
  done
  if $param_ifs; then
    false
  else
    ifs=$nl
    param_ifs=true
  fi
  IFS=$IFS_save
else
  if $param_ifs; then
    false
  else
    ifs=' '
    param_ifs=true
  fi
fi

if $param_ifs && test x"$ifs" = "x\n"; then
  ifs=$nl
fi

IFS_save=$IFS
IFS=$nl

new_data=""
data=$list
for list in $data; do
  if $param_ifs; then
    IFS=$ifs
  else
    IFS=$IFS_save
  fi
  
  if $param_grep; then
    new_list=""
    for item in $list; do
      if test x"$item" != "x"; then
        item=`echo $item | eval grep $grep_args`
        if test x"$item" != "x"; then
          if test x"$new_list" = "x"; then
            new_list="$item"
          else
            new_list="${new_list}${IFS}${item}"
          fi
        fi
      fi
    done
    list=$new_list
  fi
  
  if $param_rm_headers; then
    new_list=""
    for item in $list; do
      item=`echo $item | grep -v '\.h$'`
      if test x"$item" != "x"; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi

  if $param_rm_cfiles; then
    new_list=""
    for item in $list; do
      item=`echo $item | grep -v '\.c$'`
      if test x"$item" != "x"; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi

  if $param_rm_cxxfiles; then
    new_list=""
    for item in $list; do
      if expr "$item" : '.*\.cxx$' > /dev/null || \
         expr "$item" : '.*\.cpp$' > /dev/null || \
         expr "$item" : '.*\.CPP$' > /dev/null || \
         expr "$item" : '.*\.c++$' > /dev/null || \
         expr "$item" : '.*\.C++$' > /dev/null || \
         expr "$item" : '.*\.C$' > /dev/null; then
        _nop=1
      else
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi

  if $param_rm_objects; then
    new_list=""
    for item in $list; do
      item=`echo $item | grep -v '\.o$'`
      if test x"$item" != "x"; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi

  if $param_grep_cfiles; then
    new_list=""
    for item in $list; do
      item=`echo $item | grep '\.c$'`
      if test x"$item" != "x"; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi
  
  if $param_grep_headers; then
    new_list=""
    for item in $list; do
      item=`echo $item | grep '\.h$'`
      if test x"$item" != "x"; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi
  
  if $param_grep_cxxfiles; then
    new_list=""
    for item in $list; do
      if expr "$item" : '.*\.cxx$' > /dev/null || \
         expr "$item" : '.*\.cpp$' > /dev/null || \
         expr "$item" : '.*\.CPP$' > /dev/null || \
         expr "$item" : '.*\.c++$' > /dev/null || \
         expr "$item" : '.*\.C++$' > /dev/null || \
         expr "$item" : '.*\.C$' > /dev/null; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi

  if $param_grep_objects; then
    new_list=""
    for item in $list; do
      item=`echo $item | grep '\.o$'`
      if test x"$item" != "x"; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi
  
  if $param_sed; then
    new_list=""
    for item in $list; do
      item=`echo $item | eval sed $sed_args`
      if test x"$item" != "x"; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi

  if $param_add_prefix; then
    new_list=""
    for item in $list; do
      item="${prefix}${item}"
      if test x"$new_list" = "x"; then
        new_list=$item
      else
        new_list="${new_list}${IFS}${item}"
      fi
    done
    list=$new_list
  fi
  
  if $param_rm_suffix; then
    new_list=""
    for item in $list; do
      item=`echo $item | sed 's/\.[^.]*$//'`
      if test x"$item" != "x"; then
        if test x"$new_list" = "x"; then
          new_list=$item
        else
          new_list="${new_list}${IFS}${item}"
        fi
      fi
    done
    list=$new_list
  fi
  
  if $param_suffix_ed; then
    new_list=""
    for item in $list; do
      item=`echo $item | sed 's/\.[^.]*$//'`
      item="${item}.${suffix_ed}"
      if test x"$new_list" = "x"; then
        new_list=$item
      else
        new_list="${new_list}${IFS}${item}"
      fi
    done
    list=$new_list
  fi
  
  if $param_add_suffix; then
    new_list=""
    for item in $list; do
      item="${item}${add_suffix}"
      if test x"$new_list" = "x"; then
        new_list=$item
      else
        new_list="${new_list}${IFS}${item}"
      fi
    done
    list=$new_list
  fi
  
  if test x"$list" != "x"; then
    new_data="${new_data}$list${nl}"
  fi

  IFS=$nl
done

IFS=$nl
iter_one=true
for line in $new_data; do
  if $param_merge_lines; then
    if $iter_one; then
      printf "%s" "${line}"
      iter_one=false
    else
      if $param_ifs && ! test x"$ifs" = "x$nl"; then
        printf "%s" "${ifs}$line"
      else
        printf "%s" " $line"
      fi
    fi
  else
    printf "%s\n" "${line}"
  fi
done

if $param_merge_lines; then
  printf "\n"
fi

IFS=$IFS_save
 
