################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean748828
distclean748828:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./listed
install: install-bin-120606
install-bin-120606: ./listed
	install -m 0755 -D ./listed /tmp/opt/share/formake/listed

