#!/bin/sh
#
# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
#

script_name=`basename $0`
delim="  "

print_help() {
  cat <<EOF | $0
text alignment tool
$script_name [options]
 -h   print this help
 STR  pattern indicating alignment position (default is two whitespaces)
EOF
}

while test $# -gt 0; do
  case $1 in
    -h)
      print_help
      exit 0
      ;;
    *)
      delim=$1
      ;;
  esac
  shift
done

awk >/dev/null 2>&1
if test $? -eq 127; then
  while IFS= read -r line; do
    echo "$line"
  done
  exit 0
fi

dchar=`echo -n "$delim" | sed 's/^\(.\).*/\1/'`
tbuf=`echo -n "$delim" | tr -d "$dchar"`
if test -z "$tbuf" && test "$dchar" = " "; then
  delim_simple=1
fi

tput cols >/dev/null 2>&1
if test $? -eq 127; then
  stty size >/dev/null 2>&1
  if test $? -ne 127; then
    ncols=`stty size | awk '{print $2}'`
  elif test -n "$COLUMNS"; then
    ncols=$COLUMNS
  else
    ncols=0
  fi
else
  ncols=`tput cols`
fi

while IFS= read -r line; do
  line=`echo -n "$line" | sed 's/ *$//'`
  if echo -n "$line" | grep "$delim" > /dev/null; then :; else
    echo "$line"
    continue
  fi

  if test x$delim_simple = x1; then
    left_part=`echo -n "$line" | sed "s/$delim[^$dchar].*/$delim/"`
    right_start=`echo -n "$left_part" | wc -m`
  else
    left_part=`echo -n "$line" | sed "s/$delim.*//"`
    right_start=`echo -n "$left_part$delim" | wc -m`
  fi
  right_start=`expr $right_start + 1`
  right_part=`echo -n "$line" | awk "{ print substr(\\\$0, $right_start) }"`

  lwidth=`echo -n "$left_part" | wc -m`
  rwidth=`echo -n "$right_part" | wc -m`
  right_col=`expr $ncols - $lwidth`

  line_width=`echo -n "$left_part$right_part" | wc -m`
  if test $ncols -eq 0 || test $line_width -le $ncols || test $right_col -lt 30; then
    echo "$left_part$right_part"
    continue
  fi

  echo -n "$left_part"
  left_space=`echo -n "$left_part" | sed 's/./ /g'`
  print_space=
  while test -n "$right_part"; do
    substr=`echo -n "$right_part" | awk "{print substr(\\\$0,1,$right_col)}"`
    right_part=`echo -n "$right_part" | awk "{print substr(\\\$0,$right_col+1)}" | sed 's/^ *//'`
    if test x$print_space = x1; then
      echo -n "$left_space"
    fi
    print_space=1
    echo "$substr"
  done
done

