################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean947659
distclean947659:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./abspath
install: install-bin-782195
install-bin-782195: ./abspath
	install -m 0755 -D ./abspath /tmp/opt/share/formake/abspath

