#!/bin/sh
#
# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
#


script_name=`basename $0`
orig_dir=`pwd`
nl='
'
base_dir=

_cd_param=
cd -P / >/dev/null 2>&1
if test $? -eq 0; then
  _cd_param="-P"
fi
cd "$orig_dir"

print_help() {
  printf "%s\n" "${script_name} [-b BASE_DIR] [<path> ...]"
}

abs_path() {
  _sub_orig_dir=`pwd`
  if test $# = 2; then
    _arg_orig_dir=$1
    _arg=$2
    if echo -n "$_arg" | grep "^/" > /dev/null; then
      :
    else
      _arg=`echo -n "$_arg_orig_dir/$_arg" | sed 's!//*!/!g'`
    fi
  else
    _arg=$1
  fi
  if test -e "$_arg"; then
    if test -d $_arg; then
      _file=
    else
      _file=`basename -- $_arg`
      _arg=`dirname -- $_arg`
    fi

    cd $_cd_param $_arg
    abs_path_ret=`pwd`
    if test x"$_file" != "x"; then
      abs_path_ret="$abs_path_ret/$_file"
    fi

    cd $_cd_param $_sub_orig_dir
  else
    if echo -n "$_arg" | grep "^/" > /dev/null; then
      abs_path_ret="$_arg"
    else
      abs_path_ret="$_sub_orig_dir/$_arg"
    fi
  fi
}

if test $# -eq 0; then
  IFS=$nl
  while read -r input; do
    abs_path $input
    printf "%s\n" "$abs_path_ret"
  done
  exit 0
fi

case x$1 in
  x-h|x-help|x--help)
    print_help
    exit 0
    ;;
  x-b)
    shift
    base_dir=$1
    shift
    ;;
esac

while test $# -gt 0; do
  if test -n "$base_dir"; then
    abs_path $base_dir $1
  else
    abs_path $1
  fi
  printf "%s\n" "$abs_path_ret"
  shift
done

