#!/bin/sh
#
# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
#

version_string="mkbuildroot 1.0"

script_name=`basename "$0"`

print_help() {
  cat <<EOF
$script_name SRCROOT BUILDROOT
  SRCROOT     path to a source root directory
  BUILDROOT   path to a build root directory
EOF
}

print_version() {
  echo "$version_string"
}

case x$1 in
  x-h|x-help|x--help)
    print_help
    exit 0
    ;;
esac

if test $# -ne 2; then
  echo "$script_name: error: invalid number of parameters"
  exit 1
fi

srcroot=$1
buildroot=$2

if test ! -d $srcroot; then
  echo "$script_name: error: invalid source root path"
  exit 1
fi

if test ! -d $buildroot; then
  mkdir -p $buildroot
fi

if test ! -d $buildroot; then
  echo "$script_name: error: could not create build root dir"
  exit 1
fi

orig_dir=`pwd`
cd $srcroot
srcroot=`pwd`
cd $orig_dir
cd $buildroot
buildroot=`pwd`

if test "$buildroot" != "$srcroot"; then
  if test -d $srcroot/formake; then
    cp -Rf $srcroot/formake $buildroot
  fi
fi

if test -d $buildroot/formake; then
  rm -f $buildroot/formake/*.conf
fi

exit 0
