################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean673964
distclean673964:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/bin ./mkmkmf
install: install-bin-29070
install-bin-29070: ./mkmkmf
	install -m 0755 -D ./mkmkmf /tmp/opt/bin/mkmkmf

