#!/bin/sh
#
# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
#

version_string="mkmkmf 1.0"
script_name=`basename "$0"`
script_options="$@"

op_out_file=mkmf
op_out_mkfile=Makefile
op_srcroot="."
dist_files="mkmf"

cd_param=
orig_dir=`pwd`
cd -P / >/dev/null 2>&1
if test $? -eq 0; then
  cd_param="-P"
fi
cd "$orig_dir"


print_help() {
  cat <<EOF
$script_name [options]
 -v                    print version
 -o FILE               output script file [$op_out_file]
 -srcroot PATH         specify source root dir relative path (SRCROOT) [.]
 -subdirs ..           run mkmf scripts in subdirs in specified order
 -omk FILE             output Make script [$op_out_mkfile]
 -cflags=FLAGS         C compiler flags
 -cxxflags=FLAGS       C++ compiler flags
 -prog*-name NAME      program name
 -prog*-src ..         program source files
 -prog*-ldflags=FLAGS  program linker flags
 -prog*-no-install     do not put aplication in install rule
 -lib*-name NAME       library name
 -lib*-src ..          library source files
 -lib*-ver X[.Y[.Z]]   library version in specified format
 -lib*-ldflags=FLAGS   library linker flags
 -lib*-no-install      do not put library in install rule
 -inst-bin ..          executables for install into bin directory
 -inst-sbin ..         executables for install into sbin directory
 -inst-lib ..          files and directories for install into lib directory
 -inst-libexec ..      files and directories for install into libexec directory
 -inst-inc ..          header files and directories for install into include dir
 -inst-man[0-9] ..     man files and directories for install into man directory
 -inst-doc ..          documentation files and directories for install into doc
 -inst-share ..        files and directories for install into share directory
 -inst-etc ..          files and directories for install into etc directory
EOF
}

print_version() {
  echo "$version_string"
}

abs_path() {
  _sub_orig_dir=`pwd`
  if test $# = 0; then
    abs_path_ret=
    return
  fi
  if test $# = 2; then
    _arg_orig_dir=$1
    _arg=$2
    if echo -n "$_arg" | grep "^/" > /dev/null; then
      :
    else
      _arg=`echo -n "$_arg_orig_dir/$_arg" | sed 's!//*!/!g'`
    fi
  else
    _arg=$1
  fi
  if test -e "$_arg"; then
    if test -d $_arg; then
      _file=
    else
      _file=`basename -- $_arg`
      _arg=`dirname -- $_arg`
    fi

    cd $_cd_param $_arg
    abs_path_ret=`pwd`
    if test x"$_file" != "x"; then
      abs_path_ret="$abs_path_ret/$_file"
    fi

    cd $_cd_param $_sub_orig_dir
  else
    if echo -n "$_arg" | grep "^/" > /dev/null; then
      abs_path_ret="$_arg"
    else
      abs_path_ret="$_sub_orig_dir/$_arg"
    fi
    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#//*#/#g'`
    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/*$#/#'`
    string_prev=
    while test "x$abs_path_ret" != "x$string_prev" ; do
      string_prev=$abs_path_ret
      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/[^/][^/][^/][^/]*/\.\./#/#g' | sed 's#/[^/][^/.]/\.\./#/#g' | sed 's#/[^/.][^/]/\.\./#/#g' | sed 's#/[^/.]/\.\./#/#g'`
      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#^/\.\./#/#' | sed 's#^/\.\.$#/#'`
      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/\./#/#g' | sed 's#/\.$#/#'`
    done
    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/$##' | sed 's#^$#/#'`
  fi
}

n_prefix=0
reg_prefix() {
  type=$1
  the_prefix=$2
  case $type in
    prog)
      eval pref_in_list=\$prog_${the_prefix}_in_list
      if test x$pref_in_list = x; then
        prog_prefix_list="$prog_prefix_list $the_prefix"
        eval prog_${the_prefix}_in_list=1
        n_prefix=`expr $n_prefix + 1`
      fi
      ;;
    lib)
      eval pref_in_list=\$lib_${the_prefix}_in_list
      if test x$pref_in_list = x; then
        lib_prefix_list="$lib_prefix_list $the_prefix"
        eval lib_${the_prefix}_in_list=1
        n_prefix=`expr $n_prefix + 1`
      fi
      ;;
  esac
}

prefix=
current_opt=
src_db="/tmp/mkmkmf$$_src.txt"
echo "" > $src_db
while test $# -gt 0; do
  case $1 in
    -h|-help|--help)
      print_help
      exit 0
      ;;
    -v)
      print_version
      exit 0
      ;;
    -o)
      current_opt=o
      ;;
    -srcroot)
      current_opt=srcroot
      ;;
    -subdirs)
      op_subdirs=
      current_opt=subdirs
      ;;
    -omk)
      current_opt=omk
      ;;
    -cflags=*)
      op_cflags=`echo -n "$1" | sed 's/^[^=]*=//'`
      current_opt=
      ;;
    -cxxflags=*)
      op_cxxflags=`echo -n "$1" | sed 's/^[^=]*=//'`
      current_opt=
      ;;
    -prog*-name)
      prefix=`echo -n "$1" | sed "s/-name$//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix prog $prefix
      current_opt="prog-name"
      ;;
    -prog*-src)
      prefix=`echo -n "$1" | sed "s/-src$//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix prog $prefix
      eval prog_${prefix}_src=
      current_opt=prog-src
      ;;
    -prog*-ldflags=*)
      prefix=`echo -n "$1" | sed "s/-ldflags=.*//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix prog $prefix
      _ldflags=`echo -n "$1" | sed 's/^[^=]*=//'`
      eval prog_${prefix}_ldflags=\$_ldflags
      current_opt=
      ;;
    -prog*-no-install)
      prefix=`echo -n "$1" | sed "s/-no-install$//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix prog $prefix
      eval prog_${prefix}_no_install=1
      current_opt=
      ;;
    -lib*-name)
      prefix=`echo -n "$1" | sed "s/-name$//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix lib $prefix
      use_libro=1
      current_opt="lib-name"
      ;;
    -lib*-src)
      prefix=`echo -n "$1" | sed "s/-src$//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix lib $prefix
      eval lib_${prefix}_src=
      use_libro=1
      current_opt=lib-src
      ;;
    -lib*-ver)
      prefix=`echo -n "$1" | sed "s/-ver$//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix lib $prefix
      use_libro=1
      current_opt=lib-ver
      ;;
    -lib*-ldflags=*)
      prefix=`echo -n "$1" | sed "s/-ldflags=.*//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix lib $prefix
      _ldflags=`echo -n "$1" | sed 's/^[^=]*=//'`
      eval lib_${prefix}_ldflags=\$_ldflags
      use_libro=1
      current_opt=
      ;;
    -lib*-no-install)
      prefix=`echo -n "$1" | sed "s/-no-install$//" | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | sed 's/^_*//'`
      reg_prefix lib $prefix
      eval lib_${prefix}_no_install=1
      use_libro=1
      current_opt=
      ;;
    -inst-bin)
      op_inst_bin=
      have_custom_inst_stuff=1
      current_opt=inst-bin
      ;;
    -inst-sbin)
      op_inst_sbin=
      have_custom_inst_stuff=1
      current_opt=inst-sbin
      ;;
    -inst-lib)
      op_inst_lib=
      have_custom_inst_stuff=1
      current_opt=inst-lib
      ;;
    -inst-libexec)
      op_inst_libexec=
      have_custom_inst_stuff=1
      current_opt=inst-libexec
      ;;
    -inst-inc)
      op_inst_inc=
      have_custom_inst_stuff=1
      current_opt=inst-inc
      ;;
    -inst-man[0-9])
      man_num=`echo -n "$1" | sed 's/^-inst-man//'`
      eval op_inst_man$man_num=
      have_custom_inst_stuff=1
      current_opt=inst-man
      ;;
    -inst-doc)
      op_inst_doc=
      have_custom_inst_stuff=1
      current_opt=inst-doc
      ;;
    -inst-share)
      op_inst_share=
      have_custom_inst_stuff=1
      current_opt=inst-share
      ;;
    -inst-etc)
      op_inst_etc=
      have_custom_inst_stuff=1
      current_opt=inst-etc
      ;;
    *)
      case "$current_opt" in
        o)
          op_out_file=`echo -n "$1" | sed 's/\/*$//'`
          if test -d "$op_out_file"; then
            op_out_file="$op_out_file/mkmf"
          fi
          current_opt=
          ;;
        srcroot)
          op_srcroot=`echo -n "$1" | sed 's!//*!/!g'`
          if test "$op_srcroot" != "/"; then
            op_srcroot=`echo -n "$op_srcroot" | sed 's!/*$!!'`
          fi
          current_opt=
          ;;
        subdirs)
          if echo -n "$1" | grep "^/" > /dev/null; then
            echo "$script_name: error: parameter -subdirs: absolute path not allowed: $1" >&2
            exit 1
          fi
          subdir=`echo -n "$1" | sed 's/\/*$//'`
          op_subdirs="$op_subdirs $subdir"
          ;;
        omk)
          op_out_mkfile=$1
          current_opt=
          ;;
        prog-name)
          eval prog_${prefix}_name=\$1
          current_opt=
          ;;
        prog-src)
          if cat $src_db | grep -F -x "$1:$prefix" > /dev/null; then
            :
          else
            echo "$1:$prefix" >>$src_db
            eval prog_${prefix}_src=\"\$prog_${prefix}_src \$1\"
            case "$1" in
              *.C|*.[Cc][Cc]|*.[Cc][Pp][Pp]|*.[Cc][Xx][Xx])
                eval prog_${prefix}_have_cxx=1
                have_cxx=1
                ;;
              *.c)
                eval prog_${prefix}_have_c=1
                have_c=1
                ;;
              *)
                echo "$script_name: error: bad source type $1" >&2
                exit 1
                ;;
            esac
          fi
          ;;
        lib-name)
          eval lib_${prefix}_name=\$1
          current_opt=
          ;;
        lib-src)
          if cat $src_db | grep -F -x "$1:$prefix" > /dev/null; then
            :
          else
            echo "$1:$prefix" >>$src_db
            eval lib_${prefix}_src=\"\$lib_${prefix}_src \$1\"
            case "$1" in
              *.C|*.[Cc][Cc]|*.[Cc][Pp][Pp]|*.[Cc][Xx][Xx])
                eval lib_${prefix}_have_cxx=1
                have_cxx=1
                ;;
              *.c)
                eval lib_${prefix}_have_c=1
                have_c=1
                ;;
              *)
                echo "$script_name: error: bad source type $1" >&2
                exit 1
                ;;
            esac
          fi
          ;;
        lib-ver)
          _current=`echo -n $1 | sed 's/^\([0-9]*\).*/\1/'`
          rest=`echo -n $1 | sed 's/^[0-9]*\.*//'`
          _revision=`echo -n $rest | sed 's/^\([0-9]*\).*/\1/'`
          rest=`echo -n $rest | sed 's/^[0-9]*\.*//'`
          _age=`echo -n $rest | sed 's/^\([0-9]*\).*/\1/'`
          eval lib_${prefix}_ver=\$1
          eval lib_${prefix}_current=\$_current
          eval lib_${prefix}_revision=\$_revision
          eval lib_${prefix}_age=\$_age
          current_opt=
          ;;
        inst-bin)
          op_inst_bin="$op_inst_bin $1"
          ;;
        inst-sbin)
          op_inst_sbin="$op_inst_sbin $1"
          ;;
        inst-lib)
          op_inst_lib="$op_inst_lib $1"
          ;;
        inst-libexec)
          op_inst_libexec="$op_inst_libexec $1"
          ;;
        inst-inc)
          op_inst_inc="$op_inst_inc $1"
          ;;
        inst-man)
          eval op_inst_man$man_num=\"\$op_inst_man$man_num $1\"
          ;;
        inst-doc)
          op_inst_doc="$op_inst_doc $1"
          ;;
        inst-share)
          op_inst_share="$op_inst_share $1"
          ;;
        inst-etc)
          op_inst_etc="$op_inst_etc $1"
          ;;
        *)
          echo "$script_name: error: bad option $1" >&2
          exit 1
          ;;
      esac
      ;;
  esac
  shift
done

rm -f $src_db

if test x$have_custom_inst_stuff = x1; then
  have_inst_stuff=1
fi

for prefix in $prog_prefix_list; do
  eval op_name=\$prog_${prefix}_name
  if test -z "$op_name"; then
    eval prog_${prefix}_name=\$prefix
  fi
  eval no_install=\$prog_${prefix}_no_install
  if test -z "$no_install"; then
    have_inst_stuff=1
  fi
done
for prefix in $lib_prefix_list; do
  eval op_name=\$lib_${prefix}_name
  if test -z "$op_name"; then
    eval lib_${prefix}_name=\$prefix
  fi
  eval op_ver=\$lib_${prefix}_ver
  if test -z "$op_ver"; then
    eval lib_${prefix}_ver=\"0.0.0\"
    eval lib_${prefix}_current=0
    eval lib_${prefix}_revision=0
    eval lib_${prefix}_age=0
  fi
  eval no_install=\$lib_${prefix}_no_install
  if test -z "$no_install"; then
    have_inst_stuff=1
  fi
done

formake_scripts="relpath mkrule"
echo "using the following Formake scripts: $formake_scripts"

cat <<TOP_EOF >$op_out_file
#!/bin/sh
################################################################################
# This script was generated with the following command:
#  $script_name $script_options
#
#
# Important variables to use:
#   BUILDROOT        - relative path to the build root directory
#   CONF             - name of the build config file
#   MAKEFILE         - name of output Make file
#   TOOLS            - tools used in this script
#   SUBDIRS          - subdirectories to run mkmf in
#   SCRIPT           - name of this script
#   SRCDIR           - relative path to the source directory (mkmf location)
#   SRCROOT          - relative path to the source root directory (package top dir)
#   ASB_BUILDDIR     - absolute path to the build directory (current dir)
#   SUBDIR           - current directory path from BUILDROOT
TOP_EOF

cat <<TOP_EOF >>$op_out_file

################################################################################
# BASE CONFIGURATION
export BUILDROOT=$op_srcroot
CONF="build.conf"
MAKEFILE="$op_out_mkfile"
TOOLS="$formake_scripts"
TOP_EOF
if test -n "$op_subdirs"; then
  op_subdirs=`echo -n "$op_subdirs" | sed 's/^ *//'`
  echo "SUBDIRS=\"$op_subdirs\"" >>$op_out_file
fi

cat <<"TOP_EOF" >>$op_out_file

################################################################################
# INIT
SCRIPT=`basename $0`
PATH=$FORMAKE:$PWD/$BUILDROOT/formake:$PATH
iftool -f $TOOLS || exit 1
export SRCDIR=`dirname $0 | xargs relpath ./`
SRCROOT=`relpath ./ $SRCDIR/$BUILDROOT`
ABS_BUILDDIR=`pwd`
SUBDIR=`relpath $BUILDROOT ./`

################################################################################
# READ CONFIG
#. $BUILDROOT/$CONF

################################################################################
# INIT MAKEFILE
mkrule init >$MAKEFILE
mkrule distclean $MAKEFILE >>$MAKEFILE

TOP_EOF


if test -n "$have_c$have_cxx"; then
  cat <<TOP_EOF >>$op_out_file
################################################################################
# OBJECTS
TOP_EOF
  if test x$have_c = x1; then
    echo "CFLAGS=\"$op_cflags\"" >>$op_out_file
  fi
  if test x$have_cxx = x1; then
    echo "CXXFLAGS=\"$op_cxxflags\"" >>$op_out_file
  fi
  if test x"$have_c$have_cxx" = x11; then
    echo "C_STATIC_DIR=\"c_static\"" >>$op_out_file
    echo "CXX_STATIC_DIR=\"cxx_static\"" >>$op_out_file
    if test x$use_libro = x1; then
      echo "C_PIC_DIR=\"c_pic\"" >>$op_out_file
      echo "CXX_PIC_DIR=\"cxx_pic\"" >>$op_out_file
    fi
    c_static_dir="\$C_STATIC_DIR"
    cxx_static_dir="\$CXX_STATIC_DIR"
    c_pic_dir="\$C_PIC_DIR"
    cxx_pic_dir="\$CXX_PIC_DIR"
  else
    echo "STATIC_DIR=\"_static\"" >>$op_out_file
    if test x$use_libro = x1; then
      echo "PIC_DIR=\"_pic\"" >>$op_out_file
    fi
    c_static_dir="\$STATIC_DIR"
    cxx_static_dir="\$STATIC_DIR"
    c_pic_dir="\$PIC_DIR"
    cxx_pic_dir="\$PIC_DIR"
  fi


  for prefix in $prog_prefix_list; do
    eval op_src=\$prog_${prefix}_src
    op_src=`echo -n "$op_src" | sed 's/^ *//' | sed 's/ *$//' | sed 's/  */ /g'`
    eval op_have_cxx=\$prog_${prefix}_have_cxx
    echo "${prefix}_sources=\"$op_src\"" >>$op_out_file
    if test x$op_have_cxx = x1; then
      static_cxx_src="$static_cxx_src \$${prefix}_sources"
    else
      static_c_src="$static_c_src \$${prefix}_sources"
    fi
  done
  for prefix in $lib_prefix_list; do
    eval op_src=\$lib_${prefix}_src
    op_src=`echo -n "$op_src" | sed 's/^ *//' | sed 's/ *$//' | sed 's/  */ /g'`
    eval op_have_cxx=\$lib_${prefix}_have_cxx
    echo "${prefix}_sources=\"$op_src\"" >>$op_out_file
    if test x$op_have_cxx = x1; then
      static_cxx_src="$static_cxx_src \$${prefix}_sources"
      pic_cxx_src="$pic_cxx_src \$${prefix}_sources"
    else
      static_c_src="$static_c_src \$${prefix}_sources"
      pic_c_src="$pic_c_src \$${prefix}_sources"
    fi
  done

  static_c_src=`echo -n "$static_c_src" | sed 's/^ *//' | sed 's/ *$//' | sed 's/  */ /g'`
  pic_c_src=`echo -n "$pic_c_src" | sed 's/^ *//' | sed 's/ *$//' | sed 's/  */ /g'`
  static_cxx_src=`echo -n "$static_cxx_src" | sed 's/^ *//' | sed 's/ *$//' | sed 's/  */ /g'`
  pic_cxx_src=`echo -n "$pic_cxx_src" | sed 's/^ *//' | sed 's/ *$//' | sed 's/  */ /g'`

# GENERATE COMPILATION RULES
  if test -n "$static_c_src"; then
    echo "mkrule obj -cflags=\"\$CFLAGS\" -src $static_c_src -d $c_static_dir >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$pic_c_src"; then
    echo "mkrule obj -pic -cflags=\"\$CFLAGS\" -src $pic_c_src -d $c_pic_dir >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$static_cxx_src"; then
    echo "mkrule obj -c++ -cflags=\"\$CXXFLAGS\" -src $static_cxx_src -d $cxx_static_dir >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$pic_cxx_src"; then
    echo "mkrule obj -c++ -pic -cflags=\"\$CXXFLAGS\" -src $pic_cxx_src -d $cxx_pic_dir >>\$MAKEFILE" >>$op_out_file
  fi
fi


if test -n "$prog_prefix_list"; then
  cat <<TOP_EOF >>$op_out_file

################################################################################
# APPLICATIONS
TOP_EOF

  for prefix in $prog_prefix_list; do
    eval op_name=\$prog_${prefix}_name
    eval op_ldflags=\$prog_${prefix}_ldflags
    eval op_no_install=\$prog_${prefix}_no_install
    eval op_have_cxx=\$prog_${prefix}_have_cxx

    cat <<TOP_EOF >>$op_out_file
${prefix}_name="$op_name"
${prefix}_ldflags="$op_ldflags"
TOP_EOF

    add_params="-all"
    if test x$op_no_install = x; then
      add_params="$add_params -install"
    fi
    if test x$op_have_cxx = x1; then
      add_params="$add_params -c++"
      objdir=$cxx_static_dir
    else
      objdir=$c_static_dir
    fi
    echo "mkrule prog $add_params -ldflags=\"\$${prefix}_ldflags\" -n \$${prefix}_name -objdir $objdir -sobj \$${prefix}_sources >>\$MAKEFILE" >>$op_out_file
    echo "" >>$op_out_file
  done
fi

if test -n "$lib_prefix_list"; then
  cat <<TOP_EOF >>$op_out_file
################################################################################
# LIBRARIES
TOP_EOF

  for prefix in $lib_prefix_list; do
    eval op_name=\$lib_${prefix}_name
    eval op_version=\$lib_${prefix}_ver
    eval op_ldflags=\$lib_${prefix}_ldflags
    eval op_no_install=\$lib_${prefix}_no_install
    eval op_have_cxx=\$lib_${prefix}_have_cxx

    cat <<TOP_EOF >>$op_out_file
${prefix}_name="$op_name"
${prefix}_version="$op_version"
${prefix}_ldflags="$op_ldflags"
TOP_EOF

    add_params="-all"
    if test x$op_no_install = x; then
      add_params="$add_params -install"
    fi
    if test x$op_have_cxx = x1; then
      add_params="$add_params -c++"
      static_objdir=$cxx_static_dir
      pic_objdir=$cxx_pic_dir
    else
      static_objdir=$c_static_dir
      pic_objdir=$c_pic_dir
    fi
    echo "mkrule lib $add_params -static -ldflags=\"\$${prefix}_ldflags\" -n \$${prefix}_name -ver \$${prefix}_version -objdir $static_objdir -sobj \$${prefix}_sources >>\$MAKEFILE" >>$op_out_file
    echo "mkrule lib $add_params -shared -ldflags=\"\$${prefix}_ldflags\" -n \$${prefix}_name -ver \$${prefix}_version -objdir $pic_objdir -sobj \$${prefix}_sources >>\$MAKEFILE" >>$op_out_file
    echo "" >>$op_out_file
  done
fi

  cat <<TOP_EOF >>$op_out_file
################################################################################
# CUSTOM CODE
# put your custom code here

TOP_EOF

if test x$have_custom_inst_stuff = x1; then
  cat <<TOP_EOF >>$op_out_file
################################################################################
# INSTALLATION FILES
TOP_EOF
  if test -n "$op_inst_bin"; then
    op_inst_bin=`echo -n "$op_inst_bin" | sed 's/^ *//'`
    echo "install_bin=\"$op_inst_bin\"" >>$op_out_file
    dist_files="$dist_files \$install_bin"
  fi
  if test -n "$op_inst_sbin"; then
    op_inst_sbin=`echo -n "$op_inst_sbin" | sed 's/^ *//'`
    echo "install_sbin=\"$op_inst_sbin\"" >>$op_out_file
    dist_files="$dist_files \$install_sbin"
  fi
  if test -n "$op_inst_lib"; then
    op_inst_lib=`echo -n "$op_inst_lib" | sed 's/^ *//'`
    echo "install_lib=\"$op_inst_lib\"" >>$op_out_file
    dist_files="$dist_files \$install_lib"
  fi
  if test -n "$op_inst_libexec"; then
    op_inst_libexec=`echo -n "$op_inst_libexec" | sed 's/^ *//'`
    echo "install_libexec=\"$op_inst_libexec\"" >>$op_out_file
    dist_files="$dist_files \$install_libexec"
  fi
  if test -n "$op_inst_inc"; then
    op_inst_inc=`echo -n "$op_inst_inc" | sed 's/^ *//'`
    echo "install_inc=\"$op_inst_inc\"" >>$op_out_file
    dist_files="$dist_files \$install_inc"
  fi
  if test -n "$op_inst_man0"; then
    op_inst_man0=`echo -n "$op_inst_man0" | sed 's/^ *//'`
    echo "install_man0=\"$op_inst_man0\"" >>$op_out_file
    dist_files="$dist_files \$install_man0"
  fi
  if test -n "$op_inst_man1"; then
    op_inst_man1=`echo -n "$op_inst_man1" | sed 's/^ *//'`
    echo "install_man1=\"$op_inst_man1\"" >>$op_out_file
    dist_files="$dist_files \$install_man1"
  fi
  if test -n "$op_inst_man2"; then
    op_inst_man2=`echo -n "$op_inst_man2" | sed 's/^ *//'`
    echo "install_man2=\"$op_inst_man2\"" >>$op_out_file
    dist_files="$dist_files \$install_man2"
  fi
  if test -n "$op_inst_man3"; then
    op_inst_man3=`echo -n "$op_inst_man3" | sed 's/^ *//'`
    echo "install_man3=\"$op_inst_man3\"" >>$op_out_file
    dist_files="$dist_files \$install_man3"
  fi
  if test -n "$op_inst_man4"; then
    op_inst_man4=`echo -n "$op_inst_man4" | sed 's/^ *//'`
    echo "install_man4=\"$op_inst_man4\"" >>$op_out_file
    dist_files="$dist_files \$install_man4"
  fi
  if test -n "$op_inst_man5"; then
    op_inst_man5=`echo -n "$op_inst_man5" | sed 's/^ *//'`
    echo "install_man5=\"$op_inst_man5\"" >>$op_out_file
    dist_files="$dist_files \$install_man5"
  fi
  if test -n "$op_inst_man6"; then
    op_inst_man6=`echo -n "$op_inst_man6" | sed 's/^ *//'`
    echo "install_man6=\"$op_inst_man6\"" >>$op_out_file
    dist_files="$dist_files \$install_man6"
  fi
  if test -n "$op_inst_man7"; then
    op_inst_man7=`echo -n "$op_inst_man7" | sed 's/^ *//'`
    echo "install_man7=\"$op_inst_man7\"" >>$op_out_file
    dist_files="$dist_files \$install_man7"
  fi
  if test -n "$op_inst_man8"; then
    op_inst_man8=`echo -n "$op_inst_man8" | sed 's/^ *//'`
    echo "install_man8=\"$op_inst_man8\"" >>$op_out_file
    dist_files="$dist_files \$install_man8"
  fi
  if test -n "$op_inst_man9"; then
    op_inst_man9=`echo -n "$op_inst_man9" | sed 's/^ *//'`
    echo "install_man9=\"$op_inst_man9\"" >>$op_out_file
    dist_files="$dist_files \$install_man9"
  fi
  if test -n "$op_inst_doc"; then
    op_inst_doc=`echo -n "$op_inst_doc" | sed 's/^ *//'`
    echo "install_doc=\"$op_inst_doc\"" >>$op_out_file
    dist_files="$dist_files \$install_doc"
  fi
  if test -n "$op_inst_share"; then
    op_inst_share=`echo -n "$op_inst_share" | sed 's/^ *//'`
    echo "install_share=\"$op_inst_share\"" >>$op_out_file
    dist_files="$dist_files \$install_share"
  fi
  if test -n "$op_inst_etc"; then
    op_inst_etc=`echo -n "$op_inst_etc" | sed 's/^ *//'`
    echo "install_etc=\"$op_inst_etc\"" >>$op_out_file
    dist_files="$dist_files \$install_etc"
  fi

  if test -n "$op_inst_bin"; then
    echo "mkrule install bin \$install_bin >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_sbin"; then
    echo "mkrule install sbin \$install_sbin >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_lib"; then
    echo "mkrule install lib \$install_lib >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_libexec"; then
    echo "mkrule install libexec \$install_libexec >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_inc"; then
    echo "mkrule install inc \$install_inc >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man0"; then
    echo "mkrule install man0 \$install_man0 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man1"; then
    echo "mkrule install man1 \$install_man1 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man2"; then
    echo "mkrule install man2 \$install_man2 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man3"; then
    echo "mkrule install man3 \$install_man3 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man4"; then
    echo "mkrule install man4 \$install_man4 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man5"; then
    echo "mkrule install man5 \$install_man5 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man6"; then
    echo "mkrule install man6 \$install_man6 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man7"; then
    echo "mkrule install man7 \$install_man7 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man8"; then
    echo "mkrule install man8 \$install_man8 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_man9"; then
    echo "mkrule install man9 \$install_man9 >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_doc"; then
    echo "mkrule install doc \$install_doc >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_share"; then
    echo "mkrule install share \$install_share >>\$MAKEFILE" >>$op_out_file
  fi
  if test -n "$op_inst_etc"; then
    echo "mkrule install etc \$install_etc >>\$MAKEFILE" >>$op_out_file
  fi
  echo "" >>$op_out_file
fi


cat <<TOP_EOF >>$op_out_file
################################################################################
# DIST
TOP_EOF
src_dist_files=
if test -n "$static_c_src"; then
  src_dist_files="$src_dist_files $static_c_src"
fi
if test -n "$pic_c_src"; then
  src_dist_files="$src_dist_files $pic_c_src"
fi
if test -n "$static_cxx_src"; then
  src_dist_files="$src_dist_files $static_cxx_src"
fi
if test -n "$pic_cxx_src"; then
  src_dist_files="$src_dist_files $pic_cxx_src"
fi
src_dist_files=`echo -n "$src_dist_files" | sed 's/^ *//' | tr ' ' '\n' | sort | uniq | tr '\n' ' ' | sed 's/ *$//'`
dist_files="$dist_files $src_dist_files"

if test "$op_srcroot" = "."; then
  if test -d formake; then
    opt_fscripts="abspath confighelp cstem cstem+ cfront iflib iftool install libro listed mkbuildroot mkdep optool pofig"
    formake_dist=
    for script in $opt_fscripts; do
      if test -f formake/$script; then
        formake_dist="$formake_dist formake/$script"
      fi
    done
    formake_dist=`echo -n "$formake_dist" | sed 's/^ *//'`
    dist_files="$formake_dist $dist_files"
  fi
  dist_files="configure formake/relpath formake/mkrule $dist_files"
fi

echo "dist_files=\"$dist_files\"" >>$op_out_file

if test "$op_srcroot" = "."; then
  echo "mkrule dist -n \$PACKAGE_NAME -ver \$PACKAGE_VERSION -f \$dist_files >>\$MAKEFILE || exit 1" >>$op_out_file
else
  echo "mkrule dist -f \$dist_files >>\$MAKEFILE || exit 1" >>$op_out_file
fi
echo "" >>$op_out_file



if test -n "$op_subdirs"; then
  cat <<"TOP_EOF" >>$op_out_file
################################################################################
# SUBDIRS
mkrule subdir -all -install -clean -dist -distclean -d $SUBDIRS >>$MAKEFILE
cd $ABS_BUILDDIR
for dir in $SUBDIRS; do
  test -d $dir || mkdir -p $dir
  `cd $dir; $ABS_BUILDDIR/$SRCDIR/$dir/mkmf` || exit 1
done

TOP_EOF
fi

cat <<"TOP_EOF" >>$op_out_file
################################################################################
# DONE
echo "$SUBDIR/$SCRIPT: DONE"

TOP_EOF


# ---final output---------------------------
chmod +x $op_out_file
echo "created script $op_out_file"

