#!/bin/sh

cstem="./cstem test CC=cl"

$cstem -cc
$cstem -cflags="-I. -I/usr/local/include"
$cstem -ld
$cstem -inc stdio.h stdlib.h
$cstem -def "_WIN32"
$cstem -def "WIN32"
$cstem -def __WIN32
$cstem -def "__WIN32__"
$cstem -def _WIN64
$cstem -def WIN64
$cstem -def __WIN64
$cstem -def __WIN64__
$cstem -def __TOS_WIN__
$cstem -def __WINDOWS__
$cstem -def WINNT
$cstem -def __WINNT
$cstem -def __WINNT__
$cstem -def _MSC_VER
$cstem -def _MSC_FULL_VER
$cstem -def LONG_MAX limits.h
$cstem -def INT_MAX limits.h
$cstem -def UCHAR_MAX limits.h
$cstem -def CHAR_BIT limits.h
$cstem -def "#ifdef _MSC_VER"
$cstem -def "#ifdef __unix__"
$cstem -def "CHAR_BIT == 8" INC="stdio.h" limits.h
$cstem -type uint16_t stdlib.h stdint.h
$cstem -type uint32_t stdlib.h stdint.h
$cstem -type uint32_t uint16_t stdlib.h stdint.h
$cstem -func close stdio.h stdlib.h
$cstem -func fprintf stdio.h stdlib.h
$cstem -func exit stdio.h stdlib.h
$cstem -func atexit stdio.h stdlib.h
$cstem -func atoi stdio.h stdlib.h
$cstem -func close fprintf exit atexit atoi INC="stdio.h stdlib.h"

cstem="./cstem c++ test CC=cl"

$cstem -cc
$cstem -cflags="-I. -I/usr/local/include"
$cstem -ld
$cstem -inc vector list set map queue
$cstem -inc cctype cstring cwchar
$cstem -inc iterator
$cstem -inc iostream cstdio
$cstem -inc vector list set map queue cctype cstring cwchar iterator iostream cstdio
$cstem -def LONG_MAX INT_MAX limits.h INC="climits limits"
$cstem -def LONG_MAX INT_MAX UCHAR_MAX CHAR_BIT INC="stdio.h" limits.h
$cstem -type bool

