#!/bin/sh

#export LM_LICENSE_FILE=/home/alex/heap/projects/formake/compilers/pgi/license.dat

cstem="./cstem c++ test CC=g++"
#cstem="./cstem c++ test CC=/home/alex/heap/projects/formake/compilers/pgi/linux86-64/2017/bin/pgc++"
#cstem="./cstem c++ test CC=g++"
#cstem="./cstem c++ test CC=clang++"

$cstem -cc
$cstem -cflags="-I. -I/usr/local/include"
$cstem -ld
$cstem -lib -lstdc++
$cstem -lib -lQtGui
$cstem -lib -lstdc++ -lQtGui
$cstem -inc vector list set map queue
$cstem -inc cctype cstring cwchar
$cstem -inc iterator
$cstem -inc iostream cstdio
$cstem -inc vector list set map queue cctype cstring cwchar iterator iostream cstdio
$cstem -def __unix__
$cstem -def LONG_MAX INT_MAX limits.h INC="climits limits"
$cstem -def Q_BYTE_ORDER QT_VERSION Q_DECL_EXPORT QT_VERSION_STR INC="QtCore/QtGlobal" -I/usr/include/qt4
$cstem -def "#if __unix__ == 1"
$cstem -def "#ifdef _BSD_SOURCE" INC="stdio.h"
$cstem -def "#if _BSD_SOURCE >= 0" INC="stdio.h"
$cstem -def "#ifdef X_PROTOCOL" INC="X11/X.h"
$cstem -def "#if X_PROTOCOL > 8" INC="X11/X.h"
$cstem -def _BSD_SOURCE __STDC__ __unix__ __GNUC__ X_PROTOCOL KeyPressMask LONG_MAX INT_MAX UCHAR_MAX CHAR_BIT INC="X11/X.h stdio.h" limits.h
$cstem -def "#if X_PROTOCOL > 8" -def "#ifdef __unix__" "#ifdef _BSD_SOURCE" -def "#if __unix__ == 1" "CHAR_BIT == 8" INC="X11/X.h stdio.h" limits.h
$cstem -def "X_PROTOCOL > 8" -def "__unix__" "_BSD_SOURCE" -def "__unix__ == 1" INC="X11/X.h stdio.h"
$cstem -type bool
$cstem -type qint32 QWidget QPushButton INC="QtCore/QtGlobal QtGui/QWidget QtGui/QPushButton" -I/usr/include/qt4 -lQtCore -lQtGui
$cstem -enum Qt::AlignLeft Qt::XAxis Qt::LeftButton INC="QtCore/Qt" -I/usr/include/qt4

