#!/bin/sh
################################################################################
# This script was generated with the following command:
#  mkmkmf -srcroot ../../ -inst-bin mkpackage
#
#
# Important variables to use:
#   BUILDROOT        - relative path to the build root directory
#   CONF             - name of the build config file
#   MAKEFILE         - name of output Make file
#   TOOLS            - tools used in this script
#   SUBDIRS          - subdirectories to run mkmf in
#   SCRIPT           - name of this script
#   SRCDIR           - relative path to the source directory (mkmf location)
#   SRCROOT          - relative path to the source root directory (package top dir)
#   ASB_BUILDDIR     - absolute path to the build directory (current dir)
#   SUBDIR           - current directory path from BUILDROOT

################################################################################
# BASE CONFIGURATION
export BUILDROOT=../..
CONF="build.conf"
MAKEFILE="Makefile"
TOOLS="relpath mkrule"

################################################################################
# INIT
SCRIPT=`basename $0`
PATH=$FORMAKE:$PWD/$BUILDROOT/formake:$PATH
syscap test -f $TOOLS || exit 1
export SRCDIR=`dirname $0 | xargs relpath ./`
SRCROOT=`relpath ./ $SRCDIR/$BUILDROOT`
ABS_BUILDDIR=`pwd`
SUBDIR=`relpath $BUILDROOT ./`

################################################################################
# READ CONFIG
. $BUILDROOT/$CONF

################################################################################
# INIT MAKEFILE
mkrule init >$MAKEFILE
mkrule distclean $MAKEFILE >>$MAKEFILE

################################################################################
# CUSTOM CODE
cat <<EOF >>$MAKEFILE
all: mkpackage
mkpackage: _mkpackage
	cat _mkpackage | sed 's#^share_dir=#share_dir=$PACKAGE_SHAREDIR#' > mkpackage
	chmod +x mkpackage

EOF
mkrule clean mkpackage >>$MAKEFILE

################################################################################
# INSTALLATION FILES
install_bin="mkpackage"
mkrule install bin -d $BINDIR $install_bin >>$MAKEFILE
mkrule install bin -d $PACKAGE_SHAREDIR $install_bin >>$MAKEFILE

################################################################################
# DIST
dist_files="mkmf _mkpackage"
mkrule dist -f $dist_files >>$MAKEFILE || exit 1

################################################################################
# DONE
echo "$SUBDIR/$SCRIPT: DONE"

