#!/bin/sh
#
# Formake mkcfront.tcl
#
# Copyright (c) 2015-2017, Oleksiy Chernyavskyy
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#\
exec tclsh "$0" ${1+"$@"}

set cc_config "cfront"
set cxx_config "cfront+"

set fid_src [open $argv0 r]
set fid_cc_config [open $cc_config w 0750]
set fid_cxx_config [open $cxx_config w 0750]

set script_start 0
set cc_block 1
set cx_block 1

while {[gets $fid_src line] >= 0} {
  if {$script_start != 2} {
    if {[string match "*CC_CONFIG_START*" $line] == 1} {
      incr script_start
    }
  } else {
    set cc_line 1
    set cx_line 1
    if {[string match "*CC_LINE*" $line] == 1} {
      set cx_line 0
      regsub -all {\s*#*CC_LINE} $line "" line
    } elseif {[string match "*CX_LINE*" $line] == 1} {
      set cc_line 0
      regsub -all {\s*#*CX_LINE} $line "" line
    }

    if {[string match "*CC_BLOCK_START*" $line] == 1} {
      set cc_block 1
      set cx_block 0
    } elseif {[string match "*CX_BLOCK_START*" $line] == 1} {
      set cc_block 0
      set cx_block 1
    } elseif {[string match "*BLOCK_END*" $line] == 1} {
      set cc_block 1
      set cx_block 1
    } else {
      set cxx_line $line
      if {$cc_block == 1 && $cc_line == 1} {
        regsub -all %C% $line C line
        puts $fid_cc_config $line
      }
      if {$cx_block == 1 && $cx_line == 1} {
        regsub -all %C% $cxx_line C++ cxx_line
        puts $fid_cxx_config $cxx_line
      }
    }
  }
}

close $fid_src
close $fid_cc_config
close $fid_cxx_config
exit 0


# CC_CONFIG_START
#!/bin/sh
#
# Generated by mkcfront.tcl
#
########## CC_BLOCK_START
# Formake cfront
########## CX_BLOCK_START
# Formake cfront+
########## BLOCK_END
#
# Copyright (c) 2015-2017, Oleksiy Chernyavskyy
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

################################################################################
# JUMP TO MODERN SHELL IF POSSIBLE
(test_exit_code_127_sdfjsdfksjdhfksjdhf  >/dev/null) 2>/dev/null
if test $? -ne 127; then
  if test -z "$FORMAKE_BASH_REDIRECT"; then
    FORMAKE_BASH_REDIRECTED=1
    export FORMAKE_BASH_REDIRECTED
    if test -x /bin/bash; then
      exec /bin/bash "$0" ${1+"$@"}
    elif test -x /usr/bin/bash; then
      exec /usr/bin/bash "$0" ${1+"$@"}
    elif test -x /usr/local/bin/bash; then
      exec /usr/local/bin/bash "$0" ${1+"$@"}
    else
      (bash -c "pwd" >/dev/null) 2>/dev/null
      if test $? -eq 0; then
        exec bash "$0" ${1+"$@"}
      fi
    fi
  fi
fi
FORMAKE_BASH_REDIRECTED=
export FORMAKE_BASH_REDIRECTED
################################################################################


script_name=`basename $0`
script_dir=`dirname $0`

################################################################################
# LOAD CONFIG
if test -f $script_dir/mk.conf; then
  . $script_dir/mk.conf
fi
########## CC_BLOCK_START
if test -f $script_dir/cfront.conf; then
  . $script_dir/cfront.conf
fi
########## CX_BLOCK_START
if test -f $script_dir/cfront+.conf; then
  . $script_dir/cfront+.conf
fi
########## BLOCK_END
################################################################################

print_help() {
cat <<EOF
########## CC_BLOCK_START
C compiler frontend based on cstem
########## CX_BLOCK_START
C++ compiler frontend based on cstem+
########## BLOCK_END

$script_name [ld] OPTIONS
  ld       Run in link mode
  -echo    Echo backend command without running it
  *        Any unrecognized options are passed unmodified to a
           backend compiler
EOF
}

case x$1 in
  xld)
    op_ld=1
    shift
    ;;
esac

while test $# -gt 0; do
  case "$1" in
    -h|-help|--help)
      print_help
      exit 0
      ;;
    -echo)
      op_echo=1
      ;;
    *)
      op_params="$op_params $1"
      ;;
  esac
  shift
done

op_params=`echo -n "$op_params" | sed 's/^ *//'`

########## CC_BLOCK_START
xstem=cstem
########## CX_BLOCK_START
xstem=cstem+
########## BLOCK_END
$xstem -h >/dev/null 2>&1
if test $? -ge 126; then
########## CC_BLOCK_START
  if test -f $script_dir/cstem; then
    xstem=$script_dir/cstem
  else
    echo "$script_name: error: cstem not found" >&2
    exit 1
  fi
########## CX_BLOCK_START
  if test -f $script_dir/cstem+; then
    xstem=$script_dir/cstem+
  else
    echo "$script_name: error: cstem+ not found" >&2
    exit 1
  fi
########## BLOCK_END
fi

if test x$op_ld = x; then
########## CC_BLOCK_START
  cc_cmd=`$xstem -cmd -cflags`
########## CX_BLOCK_START
  cc_cmd=`$xstem -cmd -cxxflags`
########## BLOCK_END
else
  cc_cmd=`$xstem -cmd -ldflags`
fi

echo "$cc_cmd $op_params"
if test x$op_echo = x; then
  $cc_cmd $op_params
fi

