################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean64664
distclean64664:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./mkrule
install: install-bin-544343
install-bin-544343: ./mkrule
	install -m 0755 -D ./mkrule /tmp/opt/share/formake/mkrule

