################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean726102
distclean726102:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./optool
install: install-bin-967137
install-bin-967137: ./optool
	install -m 0755 -D ./optool /tmp/opt/share/formake/optool

