################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean596759
distclean596759:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./mkbuildroot
install: install-bin-137790
install-bin-137790: ./mkbuildroot
	install -m 0755 -D ./mkbuildroot /tmp/opt/share/formake/mkbuildroot

