################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean535301
distclean535301:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./iftool
install: install-bin-119972
install-bin-119972: ./iftool
	install -m 0755 -D ./iftool /tmp/opt/share/formake/iftool

