#!/bin/sh
#
# Formake src2obj
# author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
#

version=1.0
script_name=`basename $0`
script_dir=`dirname $0`
nl='
'
op_ext='o'

################################################################################
# LOAD CONFIG
PATH=$FORMAKE:$PATH
SRC2OBJ=
if test -f $script_dir/formake.conf; then
  . $script_dir/formake.conf
fi
test -n "$FORMAKE_SRC2OBJ" && SRC2OBJ=$FORMAKE_SRC2OBJ
if test -n "$SRC2OBJ" && test -z "$SRC2OBJ_REDIRECT"; then
  export SRC2OBJ_REDIRECT=1
  $SRC2OBJ "$@"
  ret=$?
  if test $ret -ne 64; then
    exit $ret
  fi
fi
################################################################################

print_help() {
  cat <<EOF
Convert source list to object list

$script_name OPTIONS sources..
$script_name OPTIONS -
$script_name -v

Options:
  -o|-objdir DIR   object directory
  -s|-srcdir DIR   source directory
  -e|-ext EXT      object extension. 'o' by default
  sources..        list of source files
  -                read from standard input
  -v               print version
EOF
}

if test $# -eq 0; then
  echo "$script_name: error. No options specified" >&2
  exit 1
fi

current_opt=
list=
op_read_stdin=
while test $# -gt 0; do
  case "$1" in
    -h|-help|--help)
      print_help
      exit 0
      ;;
    -v)
      printf "$script_name ${version}\n"
      exit 0
      ;;
    -o|-objdir)
      current_opt=objdir
      ;;
    -s|-srcdir)
      current_opt=srcdir
      ;;
    -e|-ext)
      current_opt=ext
      ;;
    -)
      op_read_stdin=1
      shift
      break
      ;;
    *)
      case x$current_opt in
        xobjdir)
          op_objdir=`echo -n "$1" | sed 's#/*$#/#'`
          current_opt=
          ;;
        xsrcdir)
          op_srcdir=`echo -n "$1" | sed 's#/*$#/#'`
          current_opt=
          ;;
        xext)
          op_ext=`echo -n "$1" | sed 's/^\.*//'`
          current_opt=
          ;;
        x)
          list=$1
          shift
          break
          ;;
      esac
      ;;
  esac
  shift
done

while test $# -gt 0; do
  list="$list $1"
  shift
done

if test x$op_read_stdin = x1; then
  list=
  IFS_save=$IFS
  IFS=$nl
  while read input; do
    if test -z "$list"; then
      list=$input
    else
      list="$list $input"
    fi
  done
  IFS=$IFS_save
fi

if test -z "$list"; then
  exit 0
fi

for file in $list; do
  file=`echo -n "$file" | sed 's/\.[^./]*$//'`
  file="${file}.$op_ext"
  if test -n "$op_objdir"; then
    file=`basename $file`
    file="$op_objdir$file"
  elif test -n "$op_srcdir"; then
    case "$file" in
      /*)
        : ;;
      *)
        file="$op_srcdir$file"
        ;;
    esac
  fi
  echo "$file"
done

