################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean876159
distclean876159:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./libro
install: install-bin-641296
install-bin-641296: ./libro
	install -m 0755 -D ./libro /tmp/opt/share/formake/libro

