################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean354403
distclean354403:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./iflib
install: install-bin-712344
install-bin-712344: ./iflib
	install -m 0755 -D ./iflib /tmp/opt/share/formake/iflib

