#!/bin/sh
#
# Formake cfront
#
# Copyright (c) 2015-2017, Oleksiy Chernyavskyy
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

script_name=`basename $0`
script_dir=`dirname $0`

################################################################################
# LOAD CONFIG
PATH=$FORMAKE:$PATH
CFRONT=
if test -f $script_dir/formake.conf; then
  . $script_dir/formake.conf
fi
test -n "$FORMAKE_CFRONT" && CFRONT=$FORMAKE_CFRONT
if test -n "$CFRONT" && test -z "$CFRONT_REDIRECT"; then
  export CFRONT_REDIRECT=1
  $CFRONT "$@"
  ret=$?
  if test $ret -ne 64; then
    exit $ret
  fi
fi
################################################################################

print_help() {
cat <<EOF
C/C++ compiler frontend based on cstem/cstem+

$script_name OPTIONS
  -c++     Force C++ mode [autodetect]
  -echo    Echo backend command without running it
  *        Any unrecognized options are passed unmodified to a
           backend compiler
EOF
}

xstem=cstem
while test $# -gt 0; do
  case "$1" in
    -h|-help|--help)
      print_help
      exit 0
      ;;
    -c++)
      xstem=cstem+
      ;;
    -echo)
      op_echo=1
      ;;
    *.C|*.[Cc][Cc]|*.[Cc][Pp][Pp]|*.[Cc][Xx][Xx])
      op_params="$op_params $1"
      xstem=cstem+
      ;;
    *)
      op_params="$op_params $1"
      ;;
  esac
  shift
done

op_params=`echo -n "$op_params" | sed 's/^ *//'`

$xstem -h >/dev/null 2>&1
if test $? -eq 127; then
  if test -f $script_dir/$xstem; then
    xstem=$script_dir/$xstem
  else
    echo "$script_name: error: $xstem not found" >&2
    exit 1
  fi
fi

cc_cmd=`$xstem -cmd -cflags`

echo "$cc_cmd $op_params"
if test x$op_echo = x; then
  $cc_cmd $op_params
fi

