#!/bin/sh
#
# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
#

script_name=`basename $0`
script_dir=`dirname $0`

print_help() {
cat <<EOF
C/C++ compiler frontend based on cstem/cstem+

$script_name OPTIONS
  -c++     Force C++ mode [autodetect]
  -echo    Echo backend command without running it
  *        Any unrecognized options are passed unmodified to a
           backend compiler
EOF
}

xstem=cstem 
while test $# -gt 0; do
  case $1 in
    -h|-help|--help)
      print_help
      exit 0
      ;;
    -c++)
      xstem=cstem+
      ;;
    -echo)
      op_echo=1
      ;;
    *.C|*.[Cc][Cc]|*.[Cc][Pp][Pp]|*.[Cc][Xx][Xx])
      op_params="$op_params $1"
      xstem=cstem+
      ;;
    *)
      op_params="$op_params $1"
      ;;
  esac
  shift
done

op_params=`echo -n "$op_params" | sed 's/^ *//'`

if test -f $script_dir/$xstem; then
  xstem=$script_dir/$xstem
else
  $xstem -h >/dev/null 2>&1
  if test $? -ne 0; then
    echo "$script_name: error: $xstem not found" >&2
    exit 1
  fi
fi

cc_cmd=`$xstem -cmd -cflags`

echo "$cc_cmd $op_params"
if test x$op_echo = x; then
  $cc_cmd $op_params
fi

