################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean397023
distclean397023:
	rm -Rf Makefile

################################################################################
# SUBDIRS
# mkrule subdir -all -install -clean -distclean -d abspath confighelp cstem iflib iftool _install libro listed mkbuildroot mkconfigure mkdep mkmkmf mkpackage mkrule optool pofig relpath
all: subdirs

subdirs: subdir-abspath
subdir-abspath: 
	$(MAKE) -C abspath
install: install-abspath
install-abspath:
	$(MAKE) -C abspath install
clean: clean-abspath
clean-abspath:
	$(MAKE) -C abspath clean
distclean: distclean-abspath
distclean-abspath:
	$(MAKE) -C abspath distclean

subdirs: subdir-confighelp
subdir-confighelp: 
	$(MAKE) -C confighelp
install: install-confighelp
install-confighelp:
	$(MAKE) -C confighelp install
clean: clean-confighelp
clean-confighelp:
	$(MAKE) -C confighelp clean
distclean: distclean-confighelp
distclean-confighelp:
	$(MAKE) -C confighelp distclean

subdirs: subdir-cstem
subdir-cstem: 
	$(MAKE) -C cstem
install: install-cstem
install-cstem:
	$(MAKE) -C cstem install
clean: clean-cstem
clean-cstem:
	$(MAKE) -C cstem clean
distclean: distclean-cstem
distclean-cstem:
	$(MAKE) -C cstem distclean

subdirs: subdir-iflib
subdir-iflib: 
	$(MAKE) -C iflib
install: install-iflib
install-iflib:
	$(MAKE) -C iflib install
clean: clean-iflib
clean-iflib:
	$(MAKE) -C iflib clean
distclean: distclean-iflib
distclean-iflib:
	$(MAKE) -C iflib distclean

subdirs: subdir-iftool
subdir-iftool: 
	$(MAKE) -C iftool
install: install-iftool
install-iftool:
	$(MAKE) -C iftool install
clean: clean-iftool
clean-iftool:
	$(MAKE) -C iftool clean
distclean: distclean-iftool
distclean-iftool:
	$(MAKE) -C iftool distclean

subdirs: subdir-_install
subdir-_install: 
	$(MAKE) -C _install
install: install-_install
install-_install:
	$(MAKE) -C _install install
clean: clean-_install
clean-_install:
	$(MAKE) -C _install clean
distclean: distclean-_install
distclean-_install:
	$(MAKE) -C _install distclean

subdirs: subdir-libro
subdir-libro: 
	$(MAKE) -C libro
install: install-libro
install-libro:
	$(MAKE) -C libro install
clean: clean-libro
clean-libro:
	$(MAKE) -C libro clean
distclean: distclean-libro
distclean-libro:
	$(MAKE) -C libro distclean

subdirs: subdir-listed
subdir-listed: 
	$(MAKE) -C listed
install: install-listed
install-listed:
	$(MAKE) -C listed install
clean: clean-listed
clean-listed:
	$(MAKE) -C listed clean
distclean: distclean-listed
distclean-listed:
	$(MAKE) -C listed distclean

subdirs: subdir-mkbuildroot
subdir-mkbuildroot: 
	$(MAKE) -C mkbuildroot
install: install-mkbuildroot
install-mkbuildroot:
	$(MAKE) -C mkbuildroot install
clean: clean-mkbuildroot
clean-mkbuildroot:
	$(MAKE) -C mkbuildroot clean
distclean: distclean-mkbuildroot
distclean-mkbuildroot:
	$(MAKE) -C mkbuildroot distclean

subdirs: subdir-mkconfigure
subdir-mkconfigure: 
	$(MAKE) -C mkconfigure
install: install-mkconfigure
install-mkconfigure:
	$(MAKE) -C mkconfigure install
clean: clean-mkconfigure
clean-mkconfigure:
	$(MAKE) -C mkconfigure clean
distclean: distclean-mkconfigure
distclean-mkconfigure:
	$(MAKE) -C mkconfigure distclean

subdirs: subdir-mkdep
subdir-mkdep: 
	$(MAKE) -C mkdep
install: install-mkdep
install-mkdep:
	$(MAKE) -C mkdep install
clean: clean-mkdep
clean-mkdep:
	$(MAKE) -C mkdep clean
distclean: distclean-mkdep
distclean-mkdep:
	$(MAKE) -C mkdep distclean

subdirs: subdir-mkmkmf
subdir-mkmkmf: 
	$(MAKE) -C mkmkmf
install: install-mkmkmf
install-mkmkmf:
	$(MAKE) -C mkmkmf install
clean: clean-mkmkmf
clean-mkmkmf:
	$(MAKE) -C mkmkmf clean
distclean: distclean-mkmkmf
distclean-mkmkmf:
	$(MAKE) -C mkmkmf distclean

subdirs: subdir-mkpackage
subdir-mkpackage: 
	$(MAKE) -C mkpackage
install: install-mkpackage
install-mkpackage:
	$(MAKE) -C mkpackage install
clean: clean-mkpackage
clean-mkpackage:
	$(MAKE) -C mkpackage clean
distclean: distclean-mkpackage
distclean-mkpackage:
	$(MAKE) -C mkpackage distclean

subdirs: subdir-mkrule
subdir-mkrule: 
	$(MAKE) -C mkrule
install: install-mkrule
install-mkrule:
	$(MAKE) -C mkrule install
clean: clean-mkrule
clean-mkrule:
	$(MAKE) -C mkrule clean
distclean: distclean-mkrule
distclean-mkrule:
	$(MAKE) -C mkrule distclean

subdirs: subdir-optool
subdir-optool: 
	$(MAKE) -C optool
install: install-optool
install-optool:
	$(MAKE) -C optool install
clean: clean-optool
clean-optool:
	$(MAKE) -C optool clean
distclean: distclean-optool
distclean-optool:
	$(MAKE) -C optool distclean

subdirs: subdir-pofig
subdir-pofig: 
	$(MAKE) -C pofig
install: install-pofig
install-pofig:
	$(MAKE) -C pofig install
clean: clean-pofig
clean-pofig:
	$(MAKE) -C pofig clean
distclean: distclean-pofig
distclean-pofig:
	$(MAKE) -C pofig distclean

subdirs: subdir-relpath
subdir-relpath: 
	$(MAKE) -C relpath
install: install-relpath
install-relpath:
	$(MAKE) -C relpath install
clean: clean-relpath
clean-relpath:
	$(MAKE) -C relpath clean
distclean: distclean-relpath
distclean-relpath:
	$(MAKE) -C relpath distclean


