################################################################################
# INIT
# mkrule init
all:
install:
uninstall:
clean:
distclean:
dist:
dist-tree:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean-818803
distclean-818803:
	rm -Rf Makefile

################################################################################
# DIST
# mkrule dist -buildroot .. -srcdir . -f mkmf
dist$(DIST_ID):
	$(MAKE) -C .. dist
DIST_ID = 308952

dist-tree: dist-tree-308952
dist-tree-308952:
	mkdir -p ../dist_tree/src/
	cp -R -P mkmf ../dist_tree/src/mkmf

################################################################################
# SUBDIRS
# mkrule subdir -all -install -clean -dist -distclean -d abspath cfront cstem _install ldlshell ldlwrap libro listed fmkconfigure fmkpackage mkdep fmkmf fmkinstall mkrule optool relpath syscap
all: subdirs

subdirs: subdir-abspath
subdir-abspath: 
	$(MAKE) -C abspath
install: install-abspath
install-abspath:
	$(MAKE) -C abspath install
uninstall: uninstall-abspath
uninstall-abspath:
	$(MAKE) -C abspath uninstall
clean: clean-abspath
clean-abspath:
	$(MAKE) -C abspath clean
distclean: distclean-abspath
distclean-abspath:
	$(MAKE) -C abspath distclean
dist-tree: dist-tree-abspath
dist-tree-abspath:
	$(MAKE) -C abspath dist-tree

subdirs: subdir-cfront
subdir-cfront: 
	$(MAKE) -C cfront
install: install-cfront
install-cfront:
	$(MAKE) -C cfront install
uninstall: uninstall-cfront
uninstall-cfront:
	$(MAKE) -C cfront uninstall
clean: clean-cfront
clean-cfront:
	$(MAKE) -C cfront clean
distclean: distclean-cfront
distclean-cfront:
	$(MAKE) -C cfront distclean
dist-tree: dist-tree-cfront
dist-tree-cfront:
	$(MAKE) -C cfront dist-tree

subdirs: subdir-cstem
subdir-cstem: 
	$(MAKE) -C cstem
install: install-cstem
install-cstem:
	$(MAKE) -C cstem install
uninstall: uninstall-cstem
uninstall-cstem:
	$(MAKE) -C cstem uninstall
clean: clean-cstem
clean-cstem:
	$(MAKE) -C cstem clean
distclean: distclean-cstem
distclean-cstem:
	$(MAKE) -C cstem distclean
dist-tree: dist-tree-cstem
dist-tree-cstem:
	$(MAKE) -C cstem dist-tree

subdirs: subdir-_install
subdir-_install: 
	$(MAKE) -C _install
install: install-_install
install-_install:
	$(MAKE) -C _install install
uninstall: uninstall-_install
uninstall-_install:
	$(MAKE) -C _install uninstall
clean: clean-_install
clean-_install:
	$(MAKE) -C _install clean
distclean: distclean-_install
distclean-_install:
	$(MAKE) -C _install distclean
dist-tree: dist-tree-_install
dist-tree-_install:
	$(MAKE) -C _install dist-tree

subdirs: subdir-ldlshell
subdir-ldlshell: 
	$(MAKE) -C ldlshell
install: install-ldlshell
install-ldlshell:
	$(MAKE) -C ldlshell install
uninstall: uninstall-ldlshell
uninstall-ldlshell:
	$(MAKE) -C ldlshell uninstall
clean: clean-ldlshell
clean-ldlshell:
	$(MAKE) -C ldlshell clean
distclean: distclean-ldlshell
distclean-ldlshell:
	$(MAKE) -C ldlshell distclean
dist-tree: dist-tree-ldlshell
dist-tree-ldlshell:
	$(MAKE) -C ldlshell dist-tree

subdirs: subdir-ldlwrap
subdir-ldlwrap: 
	$(MAKE) -C ldlwrap
install: install-ldlwrap
install-ldlwrap:
	$(MAKE) -C ldlwrap install
uninstall: uninstall-ldlwrap
uninstall-ldlwrap:
	$(MAKE) -C ldlwrap uninstall
clean: clean-ldlwrap
clean-ldlwrap:
	$(MAKE) -C ldlwrap clean
distclean: distclean-ldlwrap
distclean-ldlwrap:
	$(MAKE) -C ldlwrap distclean
dist-tree: dist-tree-ldlwrap
dist-tree-ldlwrap:
	$(MAKE) -C ldlwrap dist-tree

subdirs: subdir-libro
subdir-libro: 
	$(MAKE) -C libro
install: install-libro
install-libro:
	$(MAKE) -C libro install
uninstall: uninstall-libro
uninstall-libro:
	$(MAKE) -C libro uninstall
clean: clean-libro
clean-libro:
	$(MAKE) -C libro clean
distclean: distclean-libro
distclean-libro:
	$(MAKE) -C libro distclean
dist-tree: dist-tree-libro
dist-tree-libro:
	$(MAKE) -C libro dist-tree

subdirs: subdir-listed
subdir-listed: 
	$(MAKE) -C listed
install: install-listed
install-listed:
	$(MAKE) -C listed install
uninstall: uninstall-listed
uninstall-listed:
	$(MAKE) -C listed uninstall
clean: clean-listed
clean-listed:
	$(MAKE) -C listed clean
distclean: distclean-listed
distclean-listed:
	$(MAKE) -C listed distclean
dist-tree: dist-tree-listed
dist-tree-listed:
	$(MAKE) -C listed dist-tree

subdirs: subdir-fmkconfigure
subdir-fmkconfigure: 
	$(MAKE) -C fmkconfigure
install: install-fmkconfigure
install-fmkconfigure:
	$(MAKE) -C fmkconfigure install
uninstall: uninstall-fmkconfigure
uninstall-fmkconfigure:
	$(MAKE) -C fmkconfigure uninstall
clean: clean-fmkconfigure
clean-fmkconfigure:
	$(MAKE) -C fmkconfigure clean
distclean: distclean-fmkconfigure
distclean-fmkconfigure:
	$(MAKE) -C fmkconfigure distclean
dist-tree: dist-tree-fmkconfigure
dist-tree-fmkconfigure:
	$(MAKE) -C fmkconfigure dist-tree

subdirs: subdir-fmkpackage
subdir-fmkpackage: 
	$(MAKE) -C fmkpackage
install: install-fmkpackage
install-fmkpackage:
	$(MAKE) -C fmkpackage install
uninstall: uninstall-fmkpackage
uninstall-fmkpackage:
	$(MAKE) -C fmkpackage uninstall
clean: clean-fmkpackage
clean-fmkpackage:
	$(MAKE) -C fmkpackage clean
distclean: distclean-fmkpackage
distclean-fmkpackage:
	$(MAKE) -C fmkpackage distclean
dist-tree: dist-tree-fmkpackage
dist-tree-fmkpackage:
	$(MAKE) -C fmkpackage dist-tree

subdirs: subdir-mkdep
subdir-mkdep: 
	$(MAKE) -C mkdep
install: install-mkdep
install-mkdep:
	$(MAKE) -C mkdep install
uninstall: uninstall-mkdep
uninstall-mkdep:
	$(MAKE) -C mkdep uninstall
clean: clean-mkdep
clean-mkdep:
	$(MAKE) -C mkdep clean
distclean: distclean-mkdep
distclean-mkdep:
	$(MAKE) -C mkdep distclean
dist-tree: dist-tree-mkdep
dist-tree-mkdep:
	$(MAKE) -C mkdep dist-tree

subdirs: subdir-fmkmf
subdir-fmkmf: 
	$(MAKE) -C fmkmf
install: install-fmkmf
install-fmkmf:
	$(MAKE) -C fmkmf install
uninstall: uninstall-fmkmf
uninstall-fmkmf:
	$(MAKE) -C fmkmf uninstall
clean: clean-fmkmf
clean-fmkmf:
	$(MAKE) -C fmkmf clean
distclean: distclean-fmkmf
distclean-fmkmf:
	$(MAKE) -C fmkmf distclean
dist-tree: dist-tree-fmkmf
dist-tree-fmkmf:
	$(MAKE) -C fmkmf dist-tree

subdirs: subdir-fmkinstall
subdir-fmkinstall: 
	$(MAKE) -C fmkinstall
install: install-fmkinstall
install-fmkinstall:
	$(MAKE) -C fmkinstall install
uninstall: uninstall-fmkinstall
uninstall-fmkinstall:
	$(MAKE) -C fmkinstall uninstall
clean: clean-fmkinstall
clean-fmkinstall:
	$(MAKE) -C fmkinstall clean
distclean: distclean-fmkinstall
distclean-fmkinstall:
	$(MAKE) -C fmkinstall distclean
dist-tree: dist-tree-fmkinstall
dist-tree-fmkinstall:
	$(MAKE) -C fmkinstall dist-tree

subdirs: subdir-mkrule
subdir-mkrule: 
	$(MAKE) -C mkrule
install: install-mkrule
install-mkrule:
	$(MAKE) -C mkrule install
uninstall: uninstall-mkrule
uninstall-mkrule:
	$(MAKE) -C mkrule uninstall
clean: clean-mkrule
clean-mkrule:
	$(MAKE) -C mkrule clean
distclean: distclean-mkrule
distclean-mkrule:
	$(MAKE) -C mkrule distclean
dist-tree: dist-tree-mkrule
dist-tree-mkrule:
	$(MAKE) -C mkrule dist-tree

subdirs: subdir-optool
subdir-optool: 
	$(MAKE) -C optool
install: install-optool
install-optool:
	$(MAKE) -C optool install
uninstall: uninstall-optool
uninstall-optool:
	$(MAKE) -C optool uninstall
clean: clean-optool
clean-optool:
	$(MAKE) -C optool clean
distclean: distclean-optool
distclean-optool:
	$(MAKE) -C optool distclean
dist-tree: dist-tree-optool
dist-tree-optool:
	$(MAKE) -C optool dist-tree

subdirs: subdir-relpath
subdir-relpath: 
	$(MAKE) -C relpath
install: install-relpath
install-relpath:
	$(MAKE) -C relpath install
uninstall: uninstall-relpath
uninstall-relpath:
	$(MAKE) -C relpath uninstall
clean: clean-relpath
clean-relpath:
	$(MAKE) -C relpath clean
distclean: distclean-relpath
distclean-relpath:
	$(MAKE) -C relpath distclean
dist-tree: dist-tree-relpath
dist-tree-relpath:
	$(MAKE) -C relpath dist-tree

subdirs: subdir-syscap
subdir-syscap: 
	$(MAKE) -C syscap
install: install-syscap
install-syscap:
	$(MAKE) -C syscap install
uninstall: uninstall-syscap
uninstall-syscap:
	$(MAKE) -C syscap uninstall
clean: clean-syscap
clean-syscap:
	$(MAKE) -C syscap clean
distclean: distclean-syscap
distclean-syscap:
	$(MAKE) -C syscap distclean
dist-tree: dist-tree-syscap
dist-tree-syscap:
	$(MAKE) -C syscap dist-tree


