#!/bin/sh

################################################################################
# base configuration variables
TOPDIR=..
SRCDIR=src
CONF="build.conf"
MAKEFILE="Makefile"

################################################################################
# go to package dir and set up PATH
cd `dirname "$0"`
PATH=$TOPDIR/mk:$PATH

################################################################################
# include toplevel config file
. $TOPDIR/$CONF

################################################################################
# set up sources and output files
PROGRAM="hello"
SOURCES="hello.c"
OBJECTS=`echo "$SOURCES" | sed 's/\.c/\.o/g'`

################################################################################
# generate makefile
cat >$MAKEFILE <<EOF
all: $PROGRAM

$PROGRAM: $OBJECTS
	$CC_CMD -o \$@ $OBJECTS $LDFLAGS

install: $PROGRAM
	install -m 0755 -D $PROGRAM $BINDIR

uninstall:
	rm -f $BINDIR/$PROGRAM

clean: clean-local

clean-local:
	rm -f $PROGRAM *.o

distclean: clean-local
	rm -f Makefile
	rm -Rf .deps

dist:
	\$(MAKE) -C $TOPDIR dist

dist-tree:
	mkdir      $TOPDIR/dist_tree/$SRCDIR
	cp mkmf    $TOPDIR/dist_tree/$SRCDIR
	cp hello.c $TOPDIR/dist_tree/$SRCDIR

EOF

rm -Rf .deps
mkdir .deps
for src in $SOURCES; do
  stem=`echo "$src" | sed 's/\.c//'`
  obj=${stem}.o
  dep=${stem}.d
  touch .deps/$dep
  cat >>$MAKEFILE <<EOF
$obj: $src
	$CC_CMD -c -o \$@ $src $CFLAGS
	@$TOPDIR/mk/mkdep $CC_CMD -c -o \$@ $src $CFLAGS > .deps/$dep
include .deps/$dep
EOF
done

echo "$SRCDIR/mkmf: DONE"

