#define CFLAGS "-O0 -g3"
#define CXXFLAGS "-O3 -g0 -I/usr/include/qt4"
#define LDFLAGS "-L. -L/home/alex/libs"
#define CXX_LDFLAGS "-L/usr/lib64/qt4"
#define MODULES "ui x11 net db"
#define ENABLE_UI "1"
#define UI_TYPE "motif"
#define XFLAGS "1"
#define XPARAM "zzz"
#define XXPARAM "qqq www eee rrr"
#define CC "cc"
#define CXX "c++"
#define PACKAGE_NAME "my_app"
#define PACKAGE_VER "1.0.0"
