#!/bin/sh

./mkconfigure -name my_app -ver 1.0.0 -build-h -iflib "-lX11 -lXt X11/Xlib.h X11/X.h X11/Intrinsic.h -cstr 'Widget *w = NULL;' -def __linux__ __unix__ __GNUC__=4 '#ifdef __linux__ && defined __unix__' -type Widget int32_t -func XtCreateWidget fprintf atoi -rval __GNUC__ __linux__ \$SRCROOT/test.c '#if (__GNUC__ == 4 && __GNUC_MINOR__ == 7) || __SIZEOF_LONG_LONG__ == 8'" -pofig -cstem -cstem+ -params="-ldflags -modules -debug -enable-ui -ui-type -xflags -xparam -xxparam" -iftool "grep ar tclsh" -sh 'test -f /etc/debian_version && echo "CONFIG_DEBIAN=1" >> build.conf' -iflib "-short -lXm Xm/Xm.h Xm/PushB.h -func XmCreatePushButton -var xmPushButtonWidgetClass -sym xmTextFieldWidgetClass -rval XmSET -enum XmSET XmTOGGLEBUTTON" -iflib "-lgif gif_lib.h" -iflib "-cxx -lQtGui -inc QtGui/QtGui"

#./configure -cflags="-O0 -g3" -cxxflags="-O3 -g0 -I/usr/include/qt4" -ldflags="-L. -L$HOME/libs" -cxx-ldflags="-L/usr/lib64/qt4" -modules ui x11 net db -enable-ui -ui-type motif -xflags -xparam zzz -xxparam qqq www eee rrr

