################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean665558
distclean665558:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake -rename install ./_install
install: install-bin-92786
install-bin-92786: ./_install
	install -m 0755 -D ./_install /tmp/opt/share/formake/install

