#!/bin/sh
#
# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
#

script_name=`basename $0`

print_help() {
cat <<EOF
command test tool
$script_name options
 -n              no echo
EOF
}

echo_status() {
  if test x$op_no_echo = x; then
    printf "$1" "$2"
  fi
}


for param in "$@"; do
  case "$param" in
    -h|-help|--help)
      print_help
      exit 0
      ;;
    -n)
      op_no_echo=1
      current_opt=
      ;;
  esac
done

command -v ls >/dev/null 2>&1
if test $? -ne 127; then
  have_command_v=1
fi
hash ls >/dev/null 2>&1
if test $? -eq 0; then
  have_hash=1
fi
type -P ls >/dev/null 2>&1
if test $? -eq 0; then
  have_type_p=1
fi
whence -p ls >/dev/null 2>&1
if test $? -eq 0; then
  have_whence_p=1
fi


tmp_file=/tmp/iftool_$$.txt
echo "" >$tmp_file
while test $# -gt 0; do
  case "$1" in
    -n)
      :
      ;;
    *)
      if grep -F -x "$1" $tmp_file > /dev/null; then
        :
      else
        echo_status "%s" "checking $1 ... "
        if test x$have_command_v = x1; then
          command -v $1 >/dev/null 2>&1
          if test $? != 0; then
            echo_status "%s\n" "Failed"
            exit 1
          fi
        elif test x$have_hash = x1; then
          hash $1 >/dev/null 2>&1
          if test $? != 0; then
            echo_status "%s\n" "Failed"
            exit 1
          fi
        elif test x$have_type_p = x1; then
          type -P $1 >/dev/null 2>&1
          if test $? != 0; then
            echo_status "%s\n" "Failed"
            exit 1
          fi
        elif test x$have_whence_p = x1; then
          whence -p $1 >/dev/null 2>&1
          if test $? != 0; then
            echo_status "%s\n" "Failed"
            exit 1
          fi
        else
          found=
          for dir in $PATH; do
            test -z "$dir" && dir=.
            if test -f "$dir/$1" && test -x "$dir/$1" ; then
              found=1
              break
            fi
          done
          if test x$found = x; then
            echo_status "%s\n" "Failed"
            exit 1
          fi
        fi
        echo_status "%s\n" "OK"
        echo "$1" >>$tmp_file
      fi
      ;;
  esac
  shift
done

rm -f $tmp_file

exit 0

