#!/bin/sh
#
# Formake fmconfigure
#
# Copyright (c) 2015-2017, Oleksiy Chernyavskyy
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

version_string="fmconfigure 1.0"

script_name=`basename "$0"`
script_options="$@"
tmp_help=/tmp/mkconf_help_$$.txt
rm -f $tmp_help
op_pkgname=package
op_pkgver=
out_file=configure
out_file_dir=.
rm_out_file=0
op_force=

print_help() {
  cat <<EOF
Generate configure script

$script_name OPTIONS
  -name NAME         package name (PACKAGE_NAME) [$op_pkgname]
  -version VERSION   package version (PACKAGE_VERSION)
  -params=".."       list of parameters for parsing
  -cc                probe and configure C compiler
  -c++               probe and configure C++ compiler
  -lib               probe the tools required for building C/C++ libraries
  -syscap ".."       probe a system with syscap test tool
  -sh CODE           insert shell string
  -build-h           generate BUILDROOT/build.h config header
  -fminstall         install Formake scripts into package formake directory
  -f                 force to overwrite existing configure script if found
  -o FILE            output script file [$out_file]
  -v                 print version
EOF
}

print_version() {
  echo "$version_string"
}

clean_exit() {
  ecode=$1
  if test $rm_out_file = 1; then
    rm -f $out_file
  fi
  exit $ecode
}

op_params=
current_opt=
syscap_index=0
while test $# -gt 0; do
  case "$1" in
    -h|-help|--help)
      print_help
      clean_exit 0
      ;;
    -v)
      print_version
      clean_exit 0
      ;;
    -name)
      current_opt=name
      ;;
    -version)
      current_opt=version
      ;;
    -params=*)
      op_params=`echo -n "$1" | sed 's/^[^=]*=//'`
      rm -f $tmp_help
      for param in $op_params; do
        echo "  $param" >> $tmp_help
      done
      current_opt=
      ;;
    -cc)
      op_cc=1
      current_opt=
      ;;
    -c++)
      op_cxx=1
      current_opt=
      ;;
    -lib)
      op_lib=1
      current_opt=
      ;;
    -syscap)
      current_opt=syscap
      ;;
    -sh)
      current_opt=sh
      ;;
    -build-h)
      op_build_h=1
      current_opt=
      ;;
    -o)
      current_opt=o
      ;;
    -fminstall)
      op_fminstall=1
      current_opt=
      ;;
    -f)
      op_force=1
      ;;
    *)
      case "$current_opt" in
        name)
          op_pkgname=$1
          current_opt=
          ;;
        version)
          op_pkgver=$1
          current_opt=
          ;;
        syscap)
          op_syscap=1
          params=$1
          eval syscap${syscap_index}_params=\$params
          syscap_index=`expr $syscap_index + 1`
          current_opt=
          ;;
        sh)
          op_sh=$1
          current_opt=
          ;;
        o)
          out_file=$1
          if test -d "$out_file"; then
            out_file="$out_file/configure"
          fi
          out_file_dir=`dirname "$out_file"`
          if test ! -d "$out_file_dir"; then
            echo "$script_name: error. Directory not found: $out_file_dir" >&2
            clean_exit 1
          fi
          op_force=1
          current_opt=
          ;;
        *)
          echo "$script_name: error. Invalid parameter: $1" >&2
          clean_exit 1
          ;;
      esac
      ;;
  esac
  shift
done

if test -f $out_file && test x$op_force = x; then
  out_file="${out_file}.new"
fi


formake_scripts="relpath mkrule"
test -n "$op_syscap$op_lib" && test -z "$op_cc$op_cxx" && op_cc=1
if test x$op_lib = x1; then
  formake_scripts="$formake_scripts libro"
fi
if test x$op_cc = x1; then
  formake_scripts="$formake_scripts cstem"
fi
if test x$op_cxx = x1; then
  formake_scripts="$formake_scripts cstem+"
fi
if test -n "$op_cc$op_cxx"; then
  formake_scripts="$formake_scripts mkdep src2obj"
fi
formake_scripts=`echo -n "$formake_scripts" | sed 's/^ *//'`

if test x$op_fminstall = x1; then
  if fminstall -h >/dev/null; then
    :
  else
    echo "$script_name: fminstall script not found" >&2
    clean_exit 1
  fi
  test -d $out_file_dir/formake || mkdir -p $out_file_dir/formake
  if test ! -d $out_file_dir/formake; then
    echo "$script_name: could not create Formake directory $out_file_dir/formake" >&2
    clean_exit 1
  fi
  fminstall -d $out_file_dir/formake -std $formake_scripts || clean_exit 1
fi

rm_out_file=1
cat <<TOP_EOF >$out_file
#!/bin/sh
################################################################################
# Generated by Formake fmconfigure
TOP_EOF
date >/dev/null 2>&1
if test $? -eq 0; then
  date | sed 's/^/# /' >>$out_file
fi

cat <<TOP_EOF >>$out_file
#
# $script_name $script_options
#
# Important variables to use:
#   PACKAGE_NAME     - package (project) name
#   PACKAGE_VERSION  - package version
#   CONF             - name of the build config file
#   CONF_H           - name of the build config header file
#   SRCROOT          - package source root directory (package top dir)
#   STD_OPTIONS      - standard configure options
#   OPTIONS          - custom configure options
#   VPATH_ON         - set to 1 if configure is run outside of the source root dir

################################################################################
# BASE CONFIGURATION
PACKAGE_NAME="$op_pkgname"
PACKAGE_VERSION="$op_pkgver"
CONF="build.conf"
CONF_H="build.h"

TOP_EOF

cat <<"TOP_EOF" >>$out_file
################################################################################
# PACKAGE PATHES
SRCROOT=`dirname $0`
PATH=$FORMAKE:`pwd`/formake:$SRCROOT/formake:$PATH

TOP_EOF

std_options="-h -help --help -prefix -exec-prefix -bindir -sbindir -libexecdir -libdir -incdir \\
             -etcdir -vardir -sharedir -mandir -docdir"
if test x$op_cc = x1; then
  std_options="$std_options -cc -cflags"
fi
if test x$op_cxx = x1; then
  std_options="$std_options -cxx -cxxflags"
fi
if test -n "$op_cc$op_cxx"; then
  std_options="$std_options -ldflags"
fi

cat <<"TOP_EOF" >>$out_file
################################################################################
# OPTIONS
#
# Variables:
#   STD_OPTIONS   - specify standard options
#   OPTIONS       - specify package specific options
#
# Note: optool script is part of Formake package. It must be installed into PACKAGE/formake
#       directory before running this script
#
# ---OPTIONAL CODE--------------------------------------------------------------
#    # C/C++ options and help
#    STD_OPTIONS="... -cc -cflags -cxx -cxxflags -ldflags"
#    
#    cat <<EOF
#    Usage: configure [options]
#      ...
#      --cc=CMD                C compiler command
#      --cflags=FLAGS          C compiler flags
#      --cxx=CMD               C++ compiler command
#      --cxxflags=FLAGS        C++ compiler flags
#      --ldflags=FLAGS         LD flags
#    EOF

TOP_EOF

cat <<TOP_EOF >>$out_file
STD_OPTIONS="$std_options"
OPTIONS="$op_params"

optool validate xh \$STD_OPTIONS \$OPTIONS - "\$@" || exit 1
if optool test any -h -help --help - "\$@"; then
  cat <<EOF
Usage: configure [options]
  --prefix=PREFIX         path to install architecture-independent files [/usr/local]
  --exec-prefix=EPREFIX   path to install architecture-dependent files [PREFIX]
  --bindir=DIR            bin path [EPREFIX/bin]
  --sbindir=DIR           sbin path [EPREFIX/sbin]
  --libexecdir=DIR        libexec path [EPREFIX/libexec]
  --libdir=DIR            lib path [EPREFIX/lib]
  --incdir=DIR            include path [PREFIX/include]
  --etcdir=DIR            etc path [PREFIX/etc]
  --vardir=DIR            var path [PREFIX/var]
  --sharedir=DIR          share path [PREFIX/share]
  --mandir=DIR            man path [SHAREDIR/man]
  --docdir=DIR            doc path [SHAREDIR/doc]
TOP_EOF
if test x$op_cc = x1; then
  cat <<TOP_EOF >>$out_file
  --cc=CMD                C compiler command
  --cflags=FLAGS          C compiler flags
TOP_EOF
fi
if test x$op_cxx = x1; then
  cat <<TOP_EOF >>$out_file
  --cxx=CMD               C++ compiler command
  --cxxflags=FLAGS        C++ compiler flags
TOP_EOF
fi
if test -n "$op_cc$op_cxx"; then
  cat <<TOP_EOF >>$out_file
  --ldflags=FLAGS         LD flags
TOP_EOF
fi
if test -f $tmp_help; then
  cat $tmp_help >>$out_file
  rm -f $tmp_help
fi
cat <<"TOP_EOF" >>$out_file
EOF
  exit 0
fi
. `optool source "$@"`

################################################################################
# VPATH
VPATH_ON=
test ! -f `basename $0` && VPATH_ON=1

################################################################################
# INIT BUILD ROOT
if test x$VPATH_ON = x1; then
  if test -f $SRCROOT/formake; then
    rm -Rf formake
    cp -Rf $SRCROOT/formake ./
    rm -f formake/*.conf
  fi
fi
rm -f configure.log
rm -f $CONF $CONF_H

TOP_EOF

cat <<TOP_EOF >>$out_file
################################################################################
# PACKAGE CONSISTENCY
#
# Here we check scripts that are used by package build automation scripts

syscap test $formake_scripts || exit 1

TOP_EOF

cat <<"TOP_EOF" >>$out_file

################################################################################
# INPUT PARAMETERS
#
# Check input parameters
# Dump parameters to a build config file
# Perform other configuration based on input parameters
#

optool dump "$@" >>$CONF
TOP_EOF
if test x"$op_build_h" = x1; then
  cat <<"TOP_EOF" >>$out_file
optool hdump "$@" >>$CONF_H
TOP_EOF
fi


cat <<"TOP_EOF" >>$out_file


################################################################################
# STATIC PARAMETERS
#
# Dump static parameters to a build config file
#

optool dump -package-name "$PACKAGE_NAME" -package-version "$PACKAGE_VERSION" >>$CONF
TOP_EOF

if test x"$op_build_h" = x1; then
  cat <<"TOP_EOF" >>$out_file
optool hdump -package-name "$PACKAGE_NAME" -package-version "$PACKAGE_VERSION" >>$CONF_H
TOP_EOF
fi

cat <<"TOP_EOF" >>$out_file


################################################################################
# STANDARD DIRECTORIES
#
# Set up standard installation directories

test -n "$PREFIX"      || PREFIX=/usr/local
test -n "$EXEC_PREFIX" || EXEC_PREFIX=$PREFIX
test -n "$BINDIR"      || BINDIR=$EXEC_PREFIX/bin
test -n "$SBINDIR"     || SBINDIR=$EXEC_PREFIX/sbin
test -n "$LIBEXECDIR"  || LIBEXECDIR=$EXEC_PREFIX/libexec
test -n "$ETCDIR"      || ETCDIR=$PREFIX/etc
test -n "$VARDIR"      || VARDIR=$PREFIX/etc
test -n "$LIBDIR"      || LIBDIR=$EXEC_PREFIX/lib
test -n "$INCDIR"      || INCDIR=$PREFIX/include
test -n "$SHAREDIR"    || SHAREDIR=$PREFIX/share
test -n "$MANDIR"      || MANDIR=$SHAREDIR/man
test -n "$DOCDIR"      || DOCDIR=$SHAREDIR/doc

DOCDIR=$DOCDIR/$PACKAGE_NAME
DATADIR=$SHAREDIR/$PACKAGE_NAME

optool dump -prefix $PREFIX -exec-prefix $EXEC_PREFIX -bindir $BINDIR -sbindir $SBINDIR \
            -libexecdir $LIBEXECDIR -libdir $LIBDIR -incdir $INCDIR -etcdir $ETCDIR \
            -vardir $VARDIR -sharedir $SHAREDIR -mandir $MANDIR -docdir $DOCDIR \
            -datadir $DATADIR >>$CONF

TOP_EOF

cat <<"TOP_EOF" >>$out_file

################################################################################
# FORMAKE CONFIG
#
# This config file is read by Formake scripts

optool dump -prefix $PREFIX -exec-prefix $EXEC_PREFIX -bindir $BINDIR -sbindir $SBINDIR \
            -libexecdir $LIBEXECDIR -libdir $LIBDIR -incdir $INCDIR -etcdir $ETCDIR \
            -vardir $VARDIR -sharedir $SHAREDIR -mandir $MANDIR -docdir $DOCDIR \
            -datadir $DATADIR \
            -package-name $PACKAGE_NAME -package-version $PACKAGE_VERSION >formake/formake.conf

TOP_EOF

cat <<"TOP_EOF" >>$out_file
################################################################################
# COMPILERS
#
# Probe and configure compilers
# Customize configuration based on compiler parameters
#
# ---OPTIONAL CODE--------------------------------------------------------------
#    # Probe and configure C compiler
#    cstem config -cc $CC -cflags="$CFLAGS" || exit 1
#
#    # Probe and configure C++ compiler
#    cstem+ config -cc $CXX -cflags="$CXXFLAGS" || exit 1

TOP_EOF
if test -n "$op_cc$op_cxx"; then
  if test x$op_cc = x1; then
    echo "cstem config -cc \$CC -cflags=\"\$CFLAGS\" || exit 1" >>$out_file
  fi
  if test x$op_cxx = x1; then
    echo "cstem+ config -cc \$CXX -cflags=\"\$CXXFLAGS\" || exit 1" >>$out_file
  fi
  echo "" >>$out_file
fi

cat <<"TOP_EOF" >>$out_file
################################################################################
# SYSTEM
#
# Probe target system parameters
# Customize configuration based on target system parameters
#
# ---OPTIONAL CODE--------------------------------------------------------------
#    # Probe 'ar' tool
#    test -n "$PROG_AR" || PROG_AR=ar
#    syscap test $PROG_AR || exit 1
#
#    # Test C compiler, linker, C flags, LD flags
#    syscap test -cc -ld -log=configure.log || exit 1
#    syscap test -with-cc -cflags="$CFLAGS" -ldflags="$LDFLAGS" -log=configure.log || exit 1
#
#    # Test C++ compiler, linker, C++ flags, LD flags
#    syscap test -cxx -ld -log=configure.log || exit 1
#    syscap test -with-cxx -cflags="$CXXFLAGS" -ldflags="$LDFLAGS" -log=configure.log || exit 1

syscap test install || exit 1

TOP_EOF
if test x$op_lib = x1; then
  cat <<"TOP_EOF" >>$out_file
test -n "$PROG_AR" || PROG_AR=ar
syscap test $PROG_AR || exit 1

TOP_EOF
fi

if test x$op_cc = x1; then
  echo "syscap test -cc -ld -log=configure.log || exit 1" >>$out_file
  echo "syscap test -with-cc -cflags=\"\$CFLAGS\" -ldflags=\"\$LDFLAGS\" -log=configure.log || exit 1" >>$out_file
  print_nl=1
fi
if test x$op_cxx = x1; then
  echo "syscap test -cxx -ld -log=configure.log || exit 1" >>$out_file
  echo "syscap test -with-cxx -cflags=\"\$CXXFLAGS\" -ldflags=\"\$LDFLAGS\" -log=configure.log || exit 1" >>$out_file
  print_nl=1
fi

idx=0
while test $idx -lt $syscap_index; do
  eval syscap_params=\$syscap${idx}_params
  if test x$op_cc = x1; then
    echo "syscap test -with-cc -with-ldflags=\"\$LDFLAGS\" $syscap_params -log=configure.log || exit 1" >>$out_file
  elif test x$op_cxx = x1; then
    echo "syscap test -with-cxx -with-ldflags=\"\$LDFLAGS\" $syscap_params -log=configure.log || exit 1" >>$out_file
  else
    echo "syscap test -with-ldflags=\"\$LDFLAGS\" $syscap_params -log=configure.log || exit 1" >>$out_file
  fi
  idx=`expr $idx + 1`
  print_nl=1
done
test x$print_nl = x1 && echo "" >>$out_file
print_nl=

cat <<"TOP_EOF" >>$out_file
################################################################################
# CUSTOM BLOCK
#
# Put custom configuration code here
TOP_EOF
if test -n "$op_sh"; then
  echo "$op_sh" >>$out_file
  echo "" >>$out_file
fi

cat <<"TOP_EOF" >>$out_file

################################################################################
# MKMF
if test -f $SRCROOT/mkmf; then
  $SRCROOT/mkmf || exit 1
fi

################################################################################
# FINISH
echo "configuring done."

TOP_EOF

chmod +x $out_file

cat <<TOP_EOF
created script $out_file
package name: $op_pkgname
package version: $op_pkgver
TOP_EOF

