################################################################################
# ALL
# mkrule all
all:
install:
clean:
distclean:

################################################################################
# DISTCLEAN
# mkrule distclean Makefile
distclean: distclean961912
distclean961912:
	rm -Rf Makefile

################################################################################
# INSTALLATION FILES
# mkrule install bin -d /tmp/opt/share/formake ./cstem ./cstem+
install: install-bin-429213
install-bin-429213: ./cstem ./cstem+
	install -m 0755 -D ./cstem /tmp/opt/share/formake/cstem
	install -m 0755 -D ./cstem+ /tmp/opt/share/formake/cstem+

